//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (OSACocoaExtensions)
- (BOOL)_osa_isLaterDate:(id)arg1;
- (BOOL)_osa_isEarlierDate:(id)arg1;
@end

