//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (OSACocoaExtensions)
+ (id)_osa_imageNamed:(id)arg1 inBundleWithIdentifier:(id)arg2;
@end

