//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableString.h>

@interface NSMutableString (OSACocoaExtensions)
- (void)_osa_standardizeEndOfLineToLineSeparator;
- (void)_osa_standardizeEndOfLineToParagraphSeparator;
- (void)_osa_standardizeEndOfLineToCR;
- (void)_osa_standardizeEndOfLineToCRLF;
- (void)_osa_standardizeEndOfLineToLF;
@end

