//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSOutlineView.h>

@interface NSOutlineView (OSACocoaExtensions)
- (void)_osa_revealItem:(id)arg1;
- (id)_osa_selectedItems;
@end

