//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSplitView.h>

@interface NSSplitView (OSACocoaExtensions)
- (double)_osa_positionOfDivider:(long long)arg1;
- (void)_osa_setPosition:(double)arg1 ofDivider:(long long)arg2;
@end

