//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSubTextStorage.h>

@interface NSSubTextStorage (OSACocoaExtensions)
- (struct _NSRange)range;
- (struct _NSRange)range;
@end

