//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextView.h>

@interface NSTextView (OSACocoaExtensions)
- (void)_osa_setContentsToAttributedString:(id)arg1;
- (void)_osa_setContentsToString:(id)arg1;
- (void)_osa_appendAttributedStringToContents:(id)arg1;
- (void)_osa_appendStringToContents:(id)arg1;
@end

