//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSADefinition.h>

@interface OSAAccessorDefinition : OSADefinition
{
}

- (id)itemIcon;
- (id)itemKind;
- (void)setStyle:(id)arg1;
- (id)style;

@end

