//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSAVerbDefinition.h>

@interface OSACommandDefinition : OSAVerbDefinition
{
}

- (BOOL)isOutlinable;
- (id)itemIcon;
- (id)itemKind;

@end

