//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSADefinition.h>

@interface OSACocoaDefinition : OSADefinition
{
}

- (void)setMethod:(id)arg1;
- (id)method;
- (void)setKey:(id)arg1;
- (id)key;
- (void)setClassName:(id)arg1;
- (id)className;

@end

