//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSADefinition.h>

@class OSADocumentationDefinition;

@interface OSAEnumerationDefinition : OSADefinition
{
    OSADocumentationDefinition *_documentation;
}

- (id)itemIcon;
- (id)itemKind;
- (void)setDocumentation:(id)arg1;
- (id)documentation;
- (void)dealloc;
- (id)init;

@end

