//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSAControlElement.h>

@interface OSAEndTryElement : OSAControlElement
{
}

+ (id)element;
- (BOOL)generateIntoText:(id)arg1 indent:(unsigned int)arg2;
- (id)init;

@end

