//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSAControlElement.h>

@interface OSAIfElement : OSAControlElement
{
}

+ (id)elementWithText:(id)arg1;
- (BOOL)generateIntoText:(id)arg1 indent:(unsigned int)arg2;
- (id)initWithText:(id)arg1;

@end

