//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAppleEventDescriptor, OSALanguage;

@interface OSALanguageInstancePrivate : NSObject
{
    OSALanguage *_language;
    struct ComponentInstanceRecord *_instance;
    BOOL _isComponentInstanceOwner;
    NSAppleEventDescriptor *_defaultTarget;
}

- (void)finalize;
- (void)dealloc;
- (id)initWithLanguage:(id)arg1;

@end

