//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAppleEventDescriptor, OSALanguage, OSALanguageInstancePrivate;

@interface OSALanguageInstance : NSObject
{
    OSALanguageInstancePrivate *_private;
}

+ (id)languageInstanceWithLanguage:(id)arg1;
- (id)richTextFromDescriptor:(id)arg1;
@property(retain) NSAppleEventDescriptor *defaultTarget;
@property(readonly) struct ComponentInstanceRecord *componentInstance;
- (void)_setComponentDefaultTarget:(id)arg1;
@property(readonly) OSALanguage *language;
- (void)dealloc;
- (id)initWithLanguage:(id)arg1;
- (id)initSharedInstanceWithLanguage:(id)arg1;

@end

