//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSAScriptElement.h>

@interface OSALongCommentElement : OSAScriptElement
{
}

+ (id)elementWithComment:(id)arg1;
- (BOOL)generateIntoText:(id)arg1 indent:(unsigned long long)arg2;
- (void)setComment:(id)arg1;
- (id)comment;
- (id)initWithComment:(id)arg1;

@end

