//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSADefinition.h>

@interface OSAPropertyDefinition : OSADefinition
{
}

- (id)itemIcon;
- (id)itemKind;
- (void)setNotInProperties:(BOOL)arg1;
- (BOOL)notInProperties;
- (void)setAccess:(id)arg1;
- (id)access;
- (void)setType:(id)arg1;
- (id)type;

@end

