//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSAScriptElement.h>

@class NSString;

@interface OSAPropertyElement : OSAScriptElement
{
    NSString *_value;
}

+ (id)elementWithProperty:(id)arg1 value:(id)arg2;
- (BOOL)generateIntoText:(id)arg1 indent:(unsigned long long)arg2;
- (id)title;
- (void)setValue:(id)arg1;
- (id)value;
- (void)setProperty:(id)arg1;
- (id)property;
- (void)dealloc;
- (id)initWithProperty:(id)arg1 value:(id)arg2;

@end

