//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSADefinition.h>

@interface OSAParameterDefinition : OSADefinition
{
}

- (id)itemIcon;
- (id)itemKind;
- (void)setOptional:(BOOL)arg1;
- (BOOL)optional;
- (void)setType:(id)arg1;
- (id)type;

@end

