//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class OSAScriptView;

@interface OSASendProc : NSObject
{
    void *_oldRefCon;
    CDUnknownFunctionPointerType _oldSendProc;
    CDUnknownFunctionPointerType _sendProc;
    OSAScriptView *_scriptView;
}

- (void)finalize;
- (void)dealloc;
- (id)initWithScriptView:(id)arg1;

@end

