//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSADefinition.h>

@interface OSASynonymDefinition : OSADefinition
{
}

- (id)itemIcon;
- (id)itemKind;

@end

