//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class OSAScriptView;

@interface OSAScriptAssistantStrategy : NSObject
{
    OSAScriptView *_scriptView;
}

- (BOOL)getItems:(id *)arg1 withInfoString:(id)arg2;
- (void)setScriptView:(id)arg1;
- (id)scriptView;
- (id)initWithScriptView:(id)arg1;

@end

