//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class OSAScriptAssistant, OSAScriptController, OSAScriptParser;

@interface OSAScriptViewPrivate : NSObject
{
    OSAScriptController *_controller;
    OSAScriptAssistant *_scriptAssistant;
    OSAScriptParser *_parser;
    BOOL _usesScriptAssistant;
}

- (void)dealloc;
- (id)init;

@end

