//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableString, OSAScriptElement;

@interface OSAScriptGenerator : NSObject
{
    OSAScriptElement *_element;
    NSMutableString *_text;
    BOOL _needsGeneration;
}

+ (id)generatorWithElement:(id)arg1;
- (id)text;
- (BOOL)generate;
- (void)setNeedsGeneration:(BOOL)arg1;
- (BOOL)needsGeneration;
- (void)setElement:(id)arg1;
- (id)element;
- (void)dealloc;
- (id)initWithElement:(id)arg1;
- (id)init;

@end

