//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface OSAScriptAssistantWindow : NSWindow
{
}

- (void)_commonAwake;
- (BOOL)hasShadow;
- (BOOL)isKeyWindow;
- (BOOL)worksWhenModal;
- (id)initWithContentRect:(struct CGRect)arg1;

@end

