//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface OSATerminologyManager : NSObject
{
    NSMutableSet *_terms;
}

+ (id)sharedTerminologyManager;
- (void)writeTerms;
- (void)_writeTerms;
- (void)readTerms;
- (void)addTerms:(id)arg1;
- (id)_pathForTerminologyCacheFile;
- (id)_cachePath;
- (void)setTerms:(id)arg1;
- (id)terms;
- (void)dealloc;
- (id)init;

@end

