//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSAScriptElement.h>

@interface OSATellElement : OSAScriptElement
{
}

+ (id)elementWithName:(id)arg1;
- (BOOL)generateIntoText:(id)arg1 indent:(unsigned int)arg2;
- (id)initWithName:(id)arg1;

@end

