//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSADefinition.h>

@class NSMutableArray, OSADocumentationDefinition;

@interface OSAVerbDefinition : OSADefinition
{
    NSMutableArray *_parameterDefinitions;
    OSADocumentationDefinition *_documentation;
}

- (void)addParameterDefinition:(id)arg1;
- (void)setDocumentation:(id)arg1;
- (id)documentation;
- (void)setParameterDefinitions:(id)arg1;
- (id)parameterDefinitions;
- (void)dealloc;
- (id)init;

@end

