//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WebKitSoftLinking : NSObject
{
}

+ (void *)lookupSymbol:(char *)arg1;
+ (void)softLink;
+ (void *)framework;

@end

