//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSXMLElement.h>

@interface NSXMLElement (SdefConvenience)
- (id)firstElementForName:(id)arg1;
- (void)addValue:(id)arg1 forAttribute:(id)arg2;
- (id)valueForAttribute:(id)arg1;
@end

