//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ScriptingBridge/SBThunk.h>

__attribute__((visibility("hidden")))
@interface SBElementThunk : SBThunk
{
    unsigned int _code;
}

+ (id)thunksForElement:(id)arg1 inDocument:(id)arg2;
- (void)invoke:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)initWithElement:(id)arg1 inDocument:(id)arg2;

@end

