//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ScriptingBridge/SBPropertyThunk.h>

__attribute__((visibility("hidden")))
@interface SBPropertyGetterThunk : SBPropertyThunk
{
}

- (void)invoke:(id)arg1;
- (id)selectorNameForName:(id)arg1;
- (id)signatureFormat;

@end

