//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ScriptingBridge/SBObject.h>

__attribute__((visibility("hidden")))
@interface SBRelativePosition : SBObject
{
}

- (id)get;
- (id)initWithParent:(id)arg1 position:(int)arg2;

@end

