//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ScriptingBridge/SBAppLocator.h>

@class NSURL;

__attribute__((visibility("hidden")))
@interface SBRemoteURLAppLocator : SBAppLocator
{
    NSURL *_url;
}

- (id)description;
- (id)sdef;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)name;
- (id)path;
- (id)initWithURL:(id)arg1;

@end

