//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ScriptingBridge/SBApplication.h>

__attribute__((visibility("hidden")))
@interface SBScriptableApplication : SBApplication
{
}

@end

