//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSAECoercerData : NSObject
{
    id coercer;
    SEL selector;
}

- (void)dealloc;
- (id)initWithCoercer:(id)arg1 selector:(SEL)arg2;

@end

