//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSConcreteData.h>

__attribute__((visibility("hidden")))
@interface _NSClrDat : NSConcreteData
{
}

- (void)encodeWithCoder:(id)arg1;
- (BOOL)_allowsDirectEncoding;
- (BOOL)_canReplaceWithDispatchDataForXPCCoder;
- (void)dealloc;

@end

