//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSConcreteMutableData.h>

__attribute__((visibility("hidden")))
@interface _NSClrDatM : NSConcreteMutableData
{
}

- (void)encodeWithCoder:(id)arg1;
- (BOOL)_canUseRealloc;
- (BOOL)_allowsDirectEncoding;
- (BOOL)_canReplaceWithDispatchDataForXPCCoder;
- (void)_freeBytes;

@end

