//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSKeySetBinding.h>

__attribute__((visibility("hidden")))
@interface _NSKVCPIvarSetBinding : NSKeySetBinding
{
    long long offset;
    CDUnknownFunctionPointerType set;
}

- (BOOL)isScalarProperty;
- (void)setValue:(id)arg1 inObject:(id)arg2;
- (id)initWithSetFunc:(CDUnknownFunctionPointerType)arg1 ivarOffset:(long long)arg2;

@end

