//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSKeyGetBinding.h>

__attribute__((visibility("hidden")))
@interface _NSKeyForwardingGetBinding : NSKeyGetBinding
{
    BOOL _isStored;
    char _padding[3];
}

- (id)getValueFromObject:(id)arg1;
- (id)initWithKey:(id)arg1 isStored:(BOOL)arg2;

@end

