//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSKeySetBinding.h>

__attribute__((visibility("hidden")))
@interface _NSKeyForwardingSetBinding : NSKeySetBinding
{
    BOOL _isStored;
    char _padding[3];
}

- (void)setValue:(id)arg1 inObject:(id)arg2;
- (id)initWithKey:(id)arg1 isStored:(BOOL)arg2;

@end

