//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/_NSPersonNameComponentsStyleFormatter.h>

__attribute__((visibility("hidden")))
@interface _NSPersonNameComponentsStyleFormatterAbbreviated : _NSPersonNameComponentsStyleFormatter
{
}

- (id)_formattedStringFromOrderedKeys:(id)arg1 components:(id)arg2 attributesByRange:(id)arg3;
- (id)_delimiterBetweenString:(id)arg1 andString:(id)arg2 isPhonetic:(BOOL)arg3;
- (id)fallbackStyleFormatter;
- (BOOL)shouldIgnoreComponentsContainingSpecialCharacters;
- (id)keysOfInterest;
- (id)abbreviatedKeys;

@end

