//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/_NSPersonNameComponentsStyleFormatterShortVariantGeneral.h>

__attribute__((visibility("hidden")))
@interface _NSPersonNameComponentsStyleFormatterGivenInitialVariant : _NSPersonNameComponentsStyleFormatterShortVariantGeneral
{
}

- (BOOL)fullComponentsAreValid:(id)arg1;
- (id)abbreviatedKeys;
- (id)keysOfInterest;
- (long long)shortNameFormat;

@end

