//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@interface _NSSharedValueTransformer : NSValueTransformer
{
}

- (BOOL)_isBooleanTransformer;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)copy;
- (BOOL)_tryRetain;
- (BOOL)_isDeallocating;
- (oneway void)release;
- (id)autorelease;
- (id)retain;

@end

