//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/_NSUndoObject.h>

__attribute__((visibility("hidden")))
@interface _NSUndoBeginMark : _NSUndoObject
{
    id _groupIdentifier;
    BOOL _isDiscardable;
}

- (id)description;
- (BOOL)isBeginMark;
- (void)setDiscardable:(BOOL)arg1;
- (BOOL)isDiscardable;
- (id)groupIdentifier;
- (void)setGroupIdentifier:(id)arg1;
- (void)dealloc;

@end

