//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet, NSString;

__attribute__((visibility("hidden")))
@interface _NSXMLDocumentExtraIvars : NSObject
{
    NSString *_MIMEType;
    NSSet *_allowedEntityURLs;
}

@end

