//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSCharacterSet.h>

__attribute__((visibility("hidden")))
@interface NSBuiltinCharacterSet : NSCharacterSet
{
    long long offset;
    id expandedset;
}

- (id)initWithCoder:(id)arg1;

@end

