//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptCommand.h>

@interface NSCloseCommand : NSScriptCommand
{
}

@property(readonly) unsigned long long saveOptions;

@end

