//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSDeserializer : NSObject
{
}

+ (id)deserializePropertyListLazilyFromData:(id)arg1 atCursor:(unsigned int *)arg2 length:(unsigned int)arg3 mutableContainers:(BOOL)arg4;
+ (id)deserializePropertyListFromData:(id)arg1 atCursor:(unsigned int *)arg2 mutableContainers:(BOOL)arg3;
+ (id)deserializePropertyListFromData:(id)arg1 mutableContainers:(BOOL)arg2;

@end

