//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptCommand.h>

@interface NSGetCommand : NSScriptCommand
{
}

- (id)performDefaultImplementation;

@end

