//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSKeyBinding.h>

@interface NSKeySetBinding : NSKeyBinding
{
}

- (BOOL)isScalarProperty;
- (void)setValue:(id)arg1 inObject:(id)arg2;
- (id)init;

@end

