//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface NSKeyBinding : NSObject
{
    Class _class;
    NSString *_key;
    void *_funcP;
}

+ (void)suppressCapitalizedKeyWarning;
- (void)dealloc;
- (void)setKey:(id)arg1;
- (id)key;
- (Class)targetClass;

@end

