//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSKeyBinding.h>

@interface NSKeyGetBinding : NSKeyBinding
{
}

- (id)getValueFromObject:(id)arg1;
- (id)init;

@end

