//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSLanguageContext : NSMutableDictionary
{
    NSMutableDictionary *_dict;
    void *_reserved;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)availableLanguageContextNames;
+ (id)languageContextWithName:(id)arg1;
+ (id)systemLanguageContext;
+ (id)defaultLanguageContext;

@end

