//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSScriptObjectSpecifier, NSString;

__attribute__((visibility("hidden")))
@interface NSPositionalSpecifierMoreIVars : NSObject
{
    NSScriptObjectSpecifier *insertionContainerSpecifier;
    NSString *insertionKey;
    unsigned long long insertionPosition;
    BOOL evaluated;
    id insertionContainer;
    BOOL specifiesSetting;
    long long insertionIndex;
    BOOL insertionReplaces;
}

@end

