//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptObjectSpecifier.h>

@interface NSPropertySpecifier : NSScriptObjectSpecifier
{
}

+ (unsigned int)_keyCodeFromRecord:(id)arg1;
- (BOOL)_putKeyFormAndDataInRecord:(id)arg1;
- (BOOL)_specifiesMultipleIndexedObjectsPerContainer;
- (BOOL)_specifiesSingleIndexedObjectPerContainer;
- (id)_specifiedIndexesOfObjectsInContainer:(id)arg1;
- (long long *)_specifiedIndicesOfObjectOrObjectsInContainer:(id)arg1 count:(long long *)arg2;
- (id)_specifiedValueInContainer:(id)arg1;

@end

