//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptObjectSpecifier.h>

@interface NSRandomSpecifier : NSScriptObjectSpecifier
{
}

+ (unsigned long long)_randomIndexForCount:(unsigned long long)arg1;
- (BOOL)_putKeyFormAndDataInRecord:(id)arg1;
- (id)_simpleDescription;
- (unsigned long long)_specifiedIndexOfObjectInContainer:(id)arg1;

@end

