//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface NSScriptClassDescriptionMoreIVars : NSObject
{
    NSString *defaultSubcontainerAttributeKey;
    NSDictionary *inverseRelationshipKeysByKey;
    NSString *presentableDescription;
    NSObject *presentableNameOrNames;
    NSString *presentablePluralName;
    NSArray *synonymDescriptions;
    BOOL isHidden;
    BOOL isFromLegacyPropertyLists;
    BOOL isSynonym;
    NSDictionary *cachedPropertyDescriptionsByKey;
    NSObject *primitiveTypeNameOrDescription;
}

@end

