//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptTypeDescription.h>

@interface NSScriptRecordTypeDescription : NSScriptTypeDescription
{
}

- (id)fieldDescriptionForKey:(id)arg1;
- (id)fieldDescriptionForAppleEventCode:(unsigned int)arg1;
- (id)coercedValue:(id)arg1;
- (SEL)objcDescriptorCreationMethodSelector;
- (SEL)objcCreationMethodSelector;
- (id)objcClassName;

@end

