//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptObjectTypeDescription.h>

__attribute__((visibility("hidden")))
@interface NSScriptFakeObjectTypeDescription : NSScriptObjectTypeDescription
{
    unsigned int _appleEventCode;
}

- (unsigned int)appleEventCode;
- (id)initWithAppleEventCode:(unsigned int)arg1;

@end

