//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSSet, NSString;

__attribute__((visibility("hidden")))
@interface NSScriptCommandDescriptionMoreIVars : NSObject
{
    NSArray *argumentDescriptions;
    NSString *presentableDescription;
    NSObject *presentableNameOrNames;
    NSString *presentableResultDescription;
    NSArray *synonymDescriptions;
    NSSet *accessGroups;
    BOOL isHidden;
    BOOL isFromLegacyPropertyLists;
    NSDictionary *cachedArgumentDescriptionsByName;
}

@end

