//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAppleEventDescriptor, NSScriptClassDescription, NSScriptTypeDescription;

__attribute__((visibility("hidden")))
@interface NSScriptExecutionContextMoreIVars : NSObject
{
    NSScriptClassDescription *rangeContainerClassDescription;
    NSScriptTypeDescription *testedObjectTypeDescription;
    int errorNumber;
    NSAppleEventDescriptor *errorOffendingObjectDescriptor;
    NSAppleEventDescriptor *errorExpectedTypeDescriptor;
}

@end

