//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSSerializer : NSObject
{
}

+ (id)serializePropertyList:(id)arg1;
+ (void)serializePropertyList:(id)arg1 intoData:(id)arg2;

@end

