//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextView.h>

__attribute__((visibility("hidden")))
@interface __NSDelegateObservingTextView : NSTextView
{
}

- (id)initWithController:(id)arg1;

@end

