//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSInspectorBarItem.h>

@class NSBox;

__attribute__((visibility("hidden")))
@interface __NSSeparatorInspectorBarItem : NSInspectorBarItem
{
    NSBox *_box;
}

- (id)view;
- (void)dealloc;

@end

