//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSharingService.h>

__attribute__((visibility("hidden")))
@interface __NSCustomSharingService : NSSharingService
{
    long long _type;
}

@property long long type; // @synthesize type=_type;

@end

