//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButtonCell.h>

__attribute__((visibility("hidden")))
@interface __NSTexturedPopUpButtonCell : NSPopUpButtonCell
{
}

- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;

@end

