//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface __NSEventDiscardInfo : NSObject
{
    unsigned long long mask;
    unsigned long long time;
}

@end

