//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface __NSWindowData : NSObject
{
    id window;
    long long windowNum;
    struct _flags {
        unsigned int visible:1;
        unsigned int hidesOnDeactivate:1;
        unsigned int modal:1;
        unsigned int _RESERVED:13;
    } flags;
}

@end

