//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColor.h>

__attribute__((visibility("hidden")))
@interface _NS_UIColorSubclasses_NSUIKitSupport : NSColor
{
}

- (double)brightnessComponent;
- (double)saturationComponent;
- (double)hueComponent;
- (double)blueComponent;
- (double)greenComponent;
- (double)redComponent;

@end

