//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColor.h>

__attribute__((visibility("hidden")))
@interface _NS_UIDeviceRGBColor_NSUIKitSupport : NSColor
{
}

- (void)getComponents:(double *)arg1;
- (long long)numberOfComponents;
- (id)colorUsingType:(long long)arg1;

@end

