//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSValue;

__attribute__((visibility("hidden")))
@interface _NSAccessibilityOverriddenAttributeUIElementValue : NSObject
{
    NSValue *_value;
    id _elementValue;
}

- (id)UIElementValue;
- (void)dealloc;
- (id)initWithUIElementValue:(id)arg1;

@end

