//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCopying-Protocol.h>
#import <AppKit/NSObject-Protocol.h>

@class NSSet;

@protocol _NSAsynchronousPreparationInputParameters <NSObject, NSCopying>
+ (NSSet *)keyPathsInvalidatingPreparedResultImmediately;
+ (NSSet *)keyPathsInvalidatingPreparedResult;
@end

