//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSModelObservingTracker.h>

@class NSCountedSet;

__attribute__((visibility("hidden")))
@interface _NSBalancedModelObservingTracker : _NSModelObservingTracker
{
    NSCountedSet *_modelAndProxyKeysSet;
}

- (void)removeObservedKey:(id)arg1;
- (void)addObservedKey:(id)arg1;
- (id)modelAndProxyKeysObserved;
- (void)_dealloc;
- (id)initWithModelObserver:(id)arg1 availableModelAndProxyKeys:(id)arg2;

@end

