//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSIndexSet;

__attribute__((visibility("hidden")))
@interface _NSBrowserDragSourceContext : NSObject
{
    long long draggedColumn;
    NSIndexSet *draggedRows;
}

@end

