//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable;

__attribute__((visibility("hidden")))
@interface _NSBinderPluginRegistry : NSObject
{
    NSMapTable *_registry;
    NSMapTable *_cachedRegistry;
}

+ (id)sharedRegistry;
- (Class)pluginClassForObject:(id)arg1 andBinderClass:(Class)arg2 requiredPluginProtocol:(id)arg3;
- (void)registerPluginClass:(Class)arg1 forObjectClass:(Class)arg2 andBinderClass:(Class)arg3;
- (void)dealloc;
- (id)init;

@end

