//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSBlockActionTarget : NSObject
{
    CDUnknownBlockType _handler;
}

+ (id)blockActionTargetWithHandler:(CDUnknownBlockType)arg1;
- (void)receiveAction:(id)arg1;
- (void)dealloc;

@end

