//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@class CALayer;

@interface _NSBorderlessLayerTreeProjectionWindow : NSWindow
{
}

- (void)orderWindow:(long long)arg1 relativeTo:(long long)arg2;
@property(readonly) CALayer *rootLayer;
- (id)initWithContentRect:(struct CGRect)arg1;

@end

