//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSColor;

@protocol _NSBoxCustomView <NSObject>
@property double cornerRadius;
@property double borderWidth;
@property(copy) NSColor *borderColor;
@property(copy) NSColor *fillColor;
@end

