//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSBrowserColumnViewScrollHandler : NSObject
{
    BOOL _wasLastScrollVertical;
    double _accum;
}

- (void)shouldSendEvent:(id)arg1 toSuperview:(char *)arg2 toSuperclass:(char *)arg3;

@end

