//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSControllerEditorSheetContext : NSObject
{
    id _delegate;
    SEL _didCommitSelector;
    void *_embeddedContextInfo;
}

@end

