//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCorrectionPanel.h>

__attribute__((visibility("hidden")))
@interface _NSCandidateBarCorrectionPanel : NSCorrectionPanel
{
}

- (void)_clearLastCorrectionPanel;
- (void)_setLastCorrectionPanelExplicitlyAccepted:(BOOL)arg1 rejected:(BOOL)arg2;
- (void)_interceptEvents;

@end

