//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <AppKit/NSRemoteViewDelegate-Protocol.h>

__attribute__((visibility("hidden")))
@interface _NSCloudSharingPostShareViewController : NSViewController <NSRemoteViewDelegate>
{
    id _remoteViewControllerStuff;
    CDUnknownBlockType _disconnectionHandler;
}

+ (void)requestViewControllerForPopover:(BOOL)arg1 withItem:(id)arg2 options:(unsigned long long)arg3 sharingServiceParameters:(id)arg4 connectionHandler:(CDUnknownBlockType)arg5;
@property(copy) CDUnknownBlockType disconnectionHandler; // @synthesize disconnectionHandler=_disconnectionHandler;
- (void)dealloc;
- (void)viewDidInvalidate:(id)arg1;
- (id)serviceViewControllerInterface;

// Remaining properties
@property(readonly) BOOL shouldRetainExportedObject;

@end

