//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSValueBinderPlugin.h>

__attribute__((visibility("hidden")))
@interface _NSColorWellPlugin : _NSValueBinderPlugin
{
}

- (id)shownValueInObject:(id)arg1;
- (void)showValue:(id)arg1 inObject:(id)arg2;
- (Class)_valueClass:(id)arg1;
- (id)objectMechanismsRequired;

@end

