//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSPointerArray;

__attribute__((visibility("hidden")))
@interface _NSCGSTransaction : NSObject
{
    NSPointerArray *_preCommitActions[3];
    NSPointerArray *_postCommitActions;
    NSMutableDictionary *_objects;
    const void *_disableUpdatesToken;
}

+ (BOOL)isActive;
+ (id)currentTransaction;
+ (void)setSynchronous:(BOOL)arg1;
+ (void)initialize;
- (void)disableUpdates;
- (void)synchronize;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)addPostCommitAction:(CDUnknownBlockType)arg1;
- (void)addActionWithOrder:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;

@end

