//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSColorPanel;

@protocol _NSColorPickerTemplate <NSObject>
- (void)createAndPrepareColorPickerWithInitialMask:(unsigned long long)arg1 colorPanel:(NSColorPanel *)arg2 completionHandle:(void (^)(NSObject<NSColorPickingCustom> *))arg3;
@end

