//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSToolbarItem.h>

__attribute__((visibility("hidden")))
@interface _NSColorPanelToolbarItem : NSToolbarItem
{
    id representedObject;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)representedObject;
- (void)setRepresentedObject:(id)arg1;

@end

