//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

@class NSIndexSet, NSMutableIndexSet, _NSCollectionViewMutableIndexPathSet;

__attribute__((visibility("hidden")))
@interface _NSCollectionViewMutableIndexPathSetEnumerator : NSEnumerator
{
    _NSCollectionViewMutableIndexPathSet *_indexPathSet;
    NSMutableIndexSet *_sectionIndexSet;
    NSIndexSet *_currentItemIndexSet;
    unsigned long long _currentSectionIndex;
    unsigned long long _lastItemIndexReturned;
}

- (void)dealloc;
- (id)nextObject;
- (id)initWithCollectionViewIndexPathSet:(id)arg1;

@end

