//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSCarbonMenuWindowTrackingAreaReference : NSObject
{
    struct CGRect rect;
    void *userData;
    struct OpaqueHIViewTrackingAreaRef *trackingRef;
    long long trackingNum;
    struct {
        unsigned int inside:1;
        unsigned int enabledDuringMouseDrag:1;
        unsigned int isCursorRect:1;
        unsigned int reserved:29;
    } f;
}

@end

