//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPanel.h>

@protocol _NSDatePickerOverlayPanelDelegate;

__attribute__((visibility("hidden")))
@interface _NSDatePickerOverlayPanel : NSPanel
{
    id <_NSDatePickerOverlayPanelDelegate> _panelDelegate;
    id _closeEventMonitor;
}

@property(retain) id _closeEventMonitor; // @synthesize _closeEventMonitor;
@property(setter=_setPanelDelegate:) id <_NSDatePickerOverlayPanelDelegate> _panelDelegate; // @synthesize _panelDelegate;
- (void)selectKeyViewPrecedingView:(id)arg1;
- (void)selectKeyViewFollowingView:(id)arg1;
- (void)resignKeyWindow;
- (BOOL)canBecomeKeyWindow;
- (BOOL)hasKeyAppearance;
- (void)applicationDidResignActive:(id)arg1;
- (BOOL)closePopoverIfNecessaryForEvent:(id)arg1;
- (void)_setVisible:(BOOL)arg1;
- (void)keyDown:(id)arg1;
- (void)cancelOperation:(id)arg1;
- (void)dealloc;

@end

