//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_semaphore;

__attribute__((visibility("hidden")))
@interface _NSDocumentSerializationSemaphore : NSObject
{
    NSObject<OS_dispatch_semaphore> *sema;
    unsigned long long timeout;
    CDUnknownBlockType timeoutHandler;
}

- (void)signal;
- (void)wait;
- (void)dealloc;
- (id)initWithTimeout:(double)arg1 handler:(CDUnknownBlockType)arg2;
- (id)init;

@end

