//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageView.h>

__attribute__((visibility("hidden")))
@interface _NSDocumentConflictImageView : NSImageView
{
}

- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

