//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSValueBinderPlugin.h>

@class NSNumber;

__attribute__((visibility("hidden")))
@interface _NSDoubleValueBinderPlugin : _NSValueBinderPlugin
{
    NSNumber *_originalMinValue;
    NSNumber *_originalMaxValue;
}

- (id)shownValueInObject:(id)arg1;
- (void)showValue:(id)arg1 inObject:(id)arg2;
- (id)objectMechanismsRequired;
- (Class)_valueClass:(id)arg1;
- (BOOL)updateCellOrControl:(id)arg1 forMaxValue:(id)arg2;
- (BOOL)updateCellOrControl:(id)arg1 forMinValue:(id)arg2;
- (void)storeMin:(BOOL)arg1 andMax:(BOOL)arg2 ofObject:(id)arg3;
- (BOOL)canSupportMinAndMaxForObject:(id)arg1;
- (void)dealloc;
- (id)initWithBinder:(id)arg1 object:(id)arg2;

@end

