//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

__attribute__((visibility("hidden")))
@interface _NSDocumentBasicAsyncOperation : NSOperation
{
    _Atomic int _state;
    _Atomic char _finishing;
}

- (void)finish;
- (BOOL)isFinished;
- (BOOL)isExecuting;
- (void)main;

@end

