//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

__attribute__((visibility("hidden")))
@interface _NSDebugTouchBarTableRowView : NSTableRowView
{
}

- (BOOL)allowsVibrancy;

@end

