//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSBinderPlugin-Protocol.h>

@protocol _NSEditorBinderPlugin <_NSBinderPlugin>
- (BOOL)conditionalBehaviorOffByDefault:(id)arg1;
- (BOOL)prefersEnabledOverEditable:(id)arg1;
@end

