//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSBinderPlugin.h>

__attribute__((visibility("hidden")))
@interface _NSEditableBinderPlugin : _NSBinderPlugin
{
}

+ (BOOL)isUsableWithObject:(id)arg1;

@end

