//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _NSExtensionQuickActionInvocation : NSObject
{
    NSArray *_requestors;
}

- (void).cxx_destruct;
- (void)performQuickAction:(id)arg1;
- (BOOL)canPerformQuickAction:(id)arg1;
- (id)initWithItemSource:(id)arg1;

@end

