//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSEventObserver : NSObject
{
    unsigned long long _mask;
    id _block;
}

- (void)invalidate;
- (void)dealloc;
- (id)initMatchingEvents:(unsigned long long)arg1 handler:(id)arg2;

@end

