//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSEvent, _NSFunctionRowCustomizationDragTarget;
@protocol NSDraggingInfo;

@protocol _NSFunctionRowCustomizationDragTargetDelegate <NSObject>
- (void)dragTarget:(_NSFunctionRowCustomizationDragTarget *)arg1 draggingConcluded:(id <NSDraggingInfo>)arg2;
- (void)dragTarget:(_NSFunctionRowCustomizationDragTarget *)arg1 draggingExited:(id <NSDraggingInfo>)arg2;
- (unsigned long long)dragTarget:(_NSFunctionRowCustomizationDragTarget *)arg1 draggingUpdated:(id <NSDraggingInfo>)arg2;
- (unsigned long long)dragTarget:(_NSFunctionRowCustomizationDragTarget *)arg1 draggingEntered:(id <NSDraggingInfo>)arg2;
- (void)dragTarget:(_NSFunctionRowCustomizationDragTarget *)arg1 mouseExited:(NSEvent *)arg2;
- (void)dragTarget:(_NSFunctionRowCustomizationDragTarget *)arg1 mouseEntered:(NSEvent *)arg2;
@end

