//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSFunctionRowCustomizationDFRItem.h>

@class NSTouchBarItem;

__attribute__((visibility("hidden")))
@interface _NSFunctionRowCustomizationFloatingDFRItem : _NSFunctionRowCustomizationDFRItem
{
    NSTouchBarItem *_representedItem;
}

@property(retain) NSTouchBarItem *representedItem; // @synthesize representedItem=_representedItem;
- (void)dealloc;
- (BOOL)isCenteredInTree:(id)arg1;
- (BOOL)isPending;

@end

