//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CABackdropLayer.h>

__attribute__((visibility("hidden")))
@interface _NSFunctionRowBackgroundBlurViewBackdropLayer : CABackdropLayer
{
    long long _enableCount;
}

+ (id)defaultValueForKey:(id)arg1;
- (void)_disable;
- (void)_enable;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)setEnabled:(BOOL)arg1;

@end

