//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _NSFullScreenTileOverlayWindowContentView : NSView
{
}

- (void)mouseDown:(id)arg1;
- (BOOL)shouldDelayWindowOrderingForEvent:(id)arg1;

@end

