//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class _NSFullScreenContentController;

__attribute__((visibility("hidden")))
@interface _NSFullScreenMenuBarCompanionController : NSObject
{
    double _menuBarReveal;
    _NSFullScreenContentController *_contentController;
}

- (void).cxx_destruct;
- (id)contentController;
- (void)setContentController:(id)arg1;
- (void)updateContentViewForMenuBarReveal;
@property(nonatomic) double menuBarReveal;
- (void)dispose;

@end

