//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet;

__attribute__((visibility("hidden")))
@interface _NSFullScreenStorage : NSObject
{
    NSSet *_participatingWindowNumbersDuringEnterTransition;
    NSSet *_participatingWindowNumbersDuringExitTransition;
    NSSet *_allSpaceParticipatingWindowNumbersDuringEnterTransition;
    unsigned long long _startingSpaceID;
}

@property unsigned long long startingSpaceID; // @synthesize startingSpaceID=_startingSpaceID;
@property(copy) NSSet *allSpaceParticipatingWindowNumbersDuringEnterTransition; // @synthesize allSpaceParticipatingWindowNumbersDuringEnterTransition=_allSpaceParticipatingWindowNumbersDuringEnterTransition;
@property(copy) NSSet *participatingWindowNumbersDuringExitTransition; // @synthesize participatingWindowNumbersDuringExitTransition=_participatingWindowNumbersDuringExitTransition;
@property(copy) NSSet *participatingWindowNumbersDuringEnterTransition; // @synthesize participatingWindowNumbersDuringEnterTransition=_participatingWindowNumbersDuringEnterTransition;
- (void)dealloc;

@end

