//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImage.h>

__attribute__((visibility("hidden")))
@interface _NSFlippedImage : NSImage
{
}

- (id)initWithRect:(struct CGRect)arg1 color:(id)arg2 ofView:(id)arg3;
- (BOOL)isFlipped;

@end

