//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSFunctionRowCustomizationDFRItem.h>

@class NSTouchBarItemTreeItemNode;

__attribute__((visibility("hidden")))
@interface _NSFunctionRowCustomizationNodeBasedDFRItem : _NSFunctionRowCustomizationDFRItem
{
    NSTouchBarItemTreeItemNode *_treeNode;
}

@property(copy) NSTouchBarItemTreeItemNode *treeNode; // @synthesize treeNode=_treeNode;
- (void)dealloc;
- (BOOL)isCenteredInTree:(id)arg1;
- (id)representedItem;

@end

