//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSPboardTypeConverter.h>

__attribute__((visibility("hidden")))
@interface _NSFilenamesPboardTypeConverter : _NSPboardTypeConverter
{
}

+ (id)_getConvertedDataFromPasteboard:(id)arg1 securityScoped:(BOOL)arg2;
+ (void)_setConvertedData:(id)arg1 pboard:(struct __CFPasteboard *)arg2 generation:(long long)arg3 inItem:(void *)arg4;

@end

