//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class NSWindow;

__attribute__((visibility("hidden")))
@interface _NSFullScreenTileWindowProxyLayer : CALayer
{
    unsigned int _wid;
    NSWindow *_window;
}

- (id)copyWithSameContents;
- (id)window;
- (unsigned int)windowID;
- (id)initWithWindowID:(unsigned int)arg1;
- (void)dealloc;

@end

