//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCompressionGroupLayout;

__attribute__((visibility("hidden")))
@interface _NSGroupPrivateData : NSObject
{
    NSCompressionGroupLayout *groupLayout;
}

- (void)dealloc;
- (id)init;

@end

