//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSFavoriteColorsStore.h>

#import <AppKit/NSFavoriteColorsStoreConcreteSubclass-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _NSGlobalPrefs10_3FavoriteColorsStore : NSFavoriteColorsStore <NSFavoriteColorsStoreConcreteSubclass>
{
    NSString *_preferenceKey;
    NSString *_domain;
}

- (id)colorsFromBacking;
- (BOOL)writeColorsToBacking:(id)arg1;
- (void)postDistributedNotification;
- (void)remoteColorsDidChange:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithPreferenceKey:(id)arg1 domain:(id)arg2;

@end

