//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSHMDDisplayLinkInvocation.h>

__attribute__((visibility("hidden")))
@interface _NSHMDDisplayLinkInvocation : NSHMDDisplayLinkInvocation
{
    double _timestamp;
    double _duration;
}

- (double)duration;
- (double)timestamp;
- (id)init;
- (id)initWithTimestamp:(double)arg1 duration:(double)arg2;

@end

