//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol _NSItemFocusingCollectionViewItem <NSObject>
- (void)refreshCollectionViewFocusState;
@end

