//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/_NSColorPickerTemplate-Protocol.h>

@class NSBundle, NSString;

__attribute__((visibility("hidden")))
@interface _NSInProcessLegacyColorPickerLoadingTemplate : NSObject <_NSColorPickerTemplate>
{
    NSBundle *_bundle;
}

- (void)createAndPrepareColorPickerWithInitialMask:(unsigned long long)arg1 colorPanel:(id)arg2 completionHandle:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)initWithBundle:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

