//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScroller.h>

__attribute__((visibility("hidden")))
@interface _NSInvisibleScroller : NSScroller
{
}

+ (double)scrollerWidthForControlSize:(unsigned long long)arg1 scrollerStyle:(long long)arg2;
- (BOOL)_shouldDoLayerPerformanceUpdates;

@end

