//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;
@protocol NSInputAlignmentItem;

@interface _NSInputAlignmentItem : NSObject
{
    id <NSInputAlignmentItem> _item;
    NSArray *_representativeGuides;
}

- (void)_updateRepresentativeGuides;
- (void)dealloc;

@end

