//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSKeyBindingManager, NSMutableArray, NSMutableString, NSSortedArray;

__attribute__((visibility("hidden")))
@interface _NSKeyBindingStateActual : NSObject
{
    NSKeyBindingManager *_currentInstance;
    NSSortedArray *_currentAtomArray;
    NSMutableString *_toInsert;
    long long _stateFlag;
    long long _repeatCount;
    NSMutableArray *_atomList;
}

@end

