//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSEventObserver.h>

__attribute__((visibility("hidden")))
@interface _NSLocalEventObserver : _NSEventObserver
{
    BOOL _isAdditive;
}

+ (void)initialize;
- (void)recomputeObserverMask;
- (void)invalidate;
- (id)initMatchingEvents:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;

@end

