//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSObservation;

__attribute__((visibility("hidden")))
@interface _NSLayoutGuideAux : NSObject
{
    NSObservation *_minXVariableObservation;
    NSObservation *_minYVariableObservation;
    NSObservation *_widthVariableObservation;
    NSObservation *_heightVariableObservation;
    unsigned long long _piercingToken;
}

- (void)dealloc;

@end

