//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSImage, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface _NSMenuServicesViewOperation : NSOperation
{
    NSString *path;
    NSMutableArray *objectsToNotify;
    NSMutableArray *completionBlocksToInvoke;
    NSImage *resultImage;
    BOOL imageIsLoaded;
}

@property(copy) NSString *path; // @synthesize path;
- (void)dealloc;
- (void)main;
- (void)finishedLoading:(id)arg1;
- (void)addCompletionBlock:(CDUnknownBlockType)arg1;

@end

