//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSNewSchoolAdapter.h>

__attribute__((visibility("hidden")))
@interface _NSNewSchoolStretchingAdapter : _NSNewSchoolAdapter
{
}

- (void)constrainAccessoryToSelf:(id)arg1;

@end

