//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSObjectAnimator.h>

__attribute__((visibility("hidden")))
@interface _NSObjectAnimator_NSSplitViewItem : _NSObjectAnimator
{
}

- (void)_uncollapsePreferringOverlay;
- (void)setCollapsed:(BOOL)arg1;
- (void)setValue:(id)arg1 forKeyPath:(id)arg2;

@end

