//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSOVRowEntry : NSObject
{
    _NSOVRowEntry *parent;
    long long childIndex;
    id item;
    long long childCount;
    id *children;
    long long *rowCounts;
    short lvl;
    struct __REFlags {
        unsigned int expandable:1;
        unsigned int expanded:1;
        unsigned int initedIsExpandableData:1;
    } _REFlags;
}

@end

