//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSBitmapImageRep;

__attribute__((visibility("hidden")))
@interface _NSOrderOutAnimationProxyWindowContentView : NSView
{
    NSBitmapImageRep *snapshot;
}

- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)setSnapshot:(id)arg1;

@end

