//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _NSOverlayDictionaryEnumerator : NSEnumerator
{
    NSArray *_keys;
    long long _i;
}

- (id)nextObject;
- (id)allObjects;
- (void)dealloc;
- (id)initWithBaseKeys:(id)arg1 overlayKeys:(id)arg2;

@end

