//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

__attribute__((visibility("hidden")))
@interface _NSOpenGLViewBackingLayer : CALayer
{
}

+ (id)defaultValueForKey:(id)arg1;
- (void)display;
- (id)actionForKey:(id)arg1;
- (void)_NS_invalidateSuggestedContentsScale;

@end

