//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSOutlineButtonCell;

__attribute__((visibility("hidden")))
@interface _NSOutlineViewReserved : NSObject
{
    NSMutableArray *autoExpandedItems;
    struct CGPoint lastHoverPoint;
    unsigned long long lastDragOperation;
    id outlineCellTrackingAreaItem;
    NSOutlineButtonCell *textOutlineCell;
    id itemBeingMade;
}

@end

