//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSOldSchoolAdapter.h>

__attribute__((visibility("hidden")))
@interface _NSOldSchoolStretchingAdapter : _NSOldSchoolAdapter
{
}

- (void)layout;
- (id)_createWidthConstraint:(double)arg1;
- (void)adapt:(id)arg1;

@end

