//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSaveAccessoryAdapter.h>

__attribute__((visibility("hidden")))
@interface _NSOldSchoolAdapter : NSSaveAccessoryAdapter
{
}

- (void)accFrameChanged:(id)arg1;
- (void)adapt:(id)arg1;
- (void)willRemoveSubview:(id)arg1;

@end

