//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSPredicateEditorRowTemplate, NSString;

__attribute__((visibility("hidden")))
@interface _NSPredicateEditorTree : NSObject
{
    NSPredicateEditorRowTemplate *template;
    NSString *title;
    NSArray *children;
    long long indexIntoTemplate;
    long long menuItemIndex;
}

@property(nonatomic) long long menuItemIndex; // @synthesize menuItemIndex;
@property(nonatomic) long long indexIntoTemplate; // @synthesize indexIntoTemplate;
@property(copy, nonatomic) NSArray *children; // @synthesize children;
@property(copy, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSPredicateEditorRowTemplate *template; // @synthesize template;
- (id)description;
- (void)dealloc;

@end

