//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _NSPboardImageTypeConverter : NSObject
{
    NSString *_sourceType;
}

+ (id)imageTypeConverterForType:(id)arg1;
- (id)_convertImageData:(id)arg1 toDataOfType:(id)arg2;
- (void)dealloc;
- (id)initWithType:(id)arg1;

@end

