//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable, NSMutableArray, NSMutableSet, NSSet;

__attribute__((visibility("hidden")))
@interface _NSPasteboardTypeCache : NSObject
{
    NSMutableArray *_cachedTypeNames;
    NSMutableSet *_cachedTypeNameUnion;
    NSMutableSet *_conformingTypeIdentifiers;
    NSMapTable *_cachedRequestOnlyTypeNames;
}

@property(readonly, nonatomic) NSMutableArray *cachedTypeNames;
- (id)requestOnlyTypesForIndex:(long long)arg1;
- (void)addRequestOnlyType:(id)arg1 forIndex:(long long)arg2;
- (id)_conformingTypeIdentifiers;
@property(readonly, nonatomic) NSSet *cachedTypeNameUnion;
- (void)dealloc;
- (id)init;

@end

