//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _NSPrintThumbnailBaseView : NSView
{
    NSView *_initialKeyView;
    NSView *_lastKeyView;
}

- (void)_setNextKeyView:(id)arg1;
- (id)_initialKeyView;

@end

