//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSPeriodicInvoker : NSObject
{
    BOOL _cancelled;
    char *_enabled;
    CDUnknownBlockType _delay;
    CDUnknownBlockType _work;
    CDUnknownBlockType _helper;
}

- (void)dealloc;
- (void)cancel;
- (void)setWorkBlock:(CDUnknownBlockType)arg1;
- (void)setDelayFunction:(CDUnknownBlockType)arg1;

@end

