//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _NSPaddedButton : NSButton
{
    NSArray *_stringsForLength;
}

@property(retain, nonatomic) NSArray *stringsForLength; // @synthesize stringsForLength=_stringsForLength;
- (struct CGSize)intrinsicContentSize;
- (void)dealloc;

@end

