//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class CALayer;

__attribute__((visibility("hidden")))
@interface _NSPopoverTransitionView : NSView
{
    CALayer *_oldContentLayer;
    CALayer *_newContentLayer;
    struct CGSize _newContentSize;
    double _delta;
}

- (void)setFrameSize:(struct CGSize)arg1;
- (id)initWithOldContent:(id)arg1 newContent:(id)arg2;

@end

