//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageView.h>

__attribute__((visibility("hidden")))
@interface _NSPageControllerImageView : NSImageView
{
}

- (void)_updateLayerMasksToBoundsFromView;

@end

