//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSTextFieldPlugin.h>

__attribute__((visibility("hidden")))
@interface _NSPlaceholderTextFieldPlugin : _NSTextFieldPlugin
{
}

- (void)showValue:(id)arg1 inObject:(id)arg2;
- (id)formattedValueInObject:(id)arg1 errorEncountered:(char *)arg2 error:(id *)arg3;
- (BOOL)acceptsMarker:(id)arg1 binding:(id)arg2 overrideWithPlaceholderIfDefined:(char *)arg3;

@end

