//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSDoubleValueBinderPlugin.h>

__attribute__((visibility("hidden")))
@interface _NSProgressIndicatorPlugin : _NSDoubleValueBinderPlugin
{
}

- (BOOL)needsAction;
- (BOOL)needsDelegate;

@end

