//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSPeriodicEventSource : NSObject
{
    double delay;
    double period;
    struct __CFRunLoopTimer *timer;
    unsigned long long errorData;
}

- (void)addTimerToModes;

@end

