//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class _NSQuickActionTouchBarItemDataSource, _NSQuickActionTouchBarPicker;

@protocol _NSQuickActionTouchBarPickerDelegate <NSObject>
- (void)cancelQuickActionTouchBarPicker:(_NSQuickActionTouchBarPicker *)arg1;
- (void)quickActionTouchBarPicker:(_NSQuickActionTouchBarPicker *)arg1 invokeQuickActionForItemDataSource:(_NSQuickActionTouchBarItemDataSource *)arg2;
@end

