//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol _NSQuickActionTouchBarClientProtocol
- (void)invokeQuickActionWithIdentifier:(NSString *)arg1;
- (void)quickActionTouchBarDidHide;
- (void)quickActionTouchBarWillShow;
@end

