//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSSet;

@protocol _NSQuickActionTouchBarServiceProtocol
- (void)enableQuickActionsWithIdentifiers:(NSSet *)arg1;
- (void)registerClient;
@end

