//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSRuleEditorCache : NSObject
{
    id rowObject;
    long long rowIndex;
    long long indentation;
}

- (id)description;

@end

