//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSSegmentWidth : NSObject
{
    unsigned long long _index;
    double _width;
    double _temporaryWidth;
}

@property double temporaryWidth; // @synthesize temporaryWidth=_temporaryWidth;
@property double width; // @synthesize width=_width;
@property unsigned long long index; // @synthesize index=_index;
- (id)initWithSegmentItem:(id)arg1;

@end

