//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSServicesContextMenuUpdater.h>

__attribute__((visibility("hidden")))
@interface _NSServicesSidecarContextMenuUpdater : _NSServicesContextMenuUpdater
{
}

- (BOOL)updateMenu:(id)arg1 withEvent:(id)arg2 withFlags:(unsigned long long)arg3;

@end

