//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSScrollingConcurrentEventVBLPreprocessFilter.h>

__attribute__((visibility("hidden")))
@interface _NSScrollingConcurrentSwipeVBLPreprocessFilter : _NSScrollingConcurrentEventVBLPreprocessFilter
{
    long long _gestureAxis;
    double _cumulativeDelta;
    double _originalOrigin;
    BOOL _isOriginalOriginDetermined;
}

@property(nonatomic) long long gestureAxis; // @synthesize gestureAxis=_gestureAxis;
- (void)scrollingVBLMonitor:(id)arg1 synchronizeForTimestamp:(double)arg2;

@end

