//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSScrollingConcurrentVBLPreprocessFilter.h>

__attribute__((visibility("hidden")))
@interface _NSScrollingConcurrentPageAlignmentAnimation : _NSScrollingConcurrentVBLPreprocessFilter
{
    struct CGPoint _initialOrigin;
    struct CGPoint _destinationOrigin;
    double _initialTimestamp;
}

@property struct CGPoint destinationOrigin; // @synthesize destinationOrigin=_destinationOrigin;
@property struct CGPoint initialOrigin; // @synthesize initialOrigin=_initialOrigin;
- (void)scrollingVBLMonitor:(id)arg1 synchronizeForTTimestamp:(double)arg2;
- (void)dealloc;
- (id)init;

@end

