//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSavePanelCustomAction.h>

#import <AppKit/NSSecureCoding-Protocol.h>

__attribute__((visibility("hidden")))
@interface _NSSavePanelCustomActionXPC : NSSavePanelCustomAction <NSSecureCoding>
{
}

+ (BOOL)supportsSecureCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

