//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPanel.h>

@class CALayer;

__attribute__((visibility("hidden")))
@interface _NSStatusItemPoofAnimator : NSPanel
{
    CALayer *_rootLayer;
    CALayer *_snapshotLayer;
}

- (void)startAnimatingWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initForAnimatingWindow:(id)arg1;
- (id)initWithStatusItem:(id)arg1;
- (void)dealloc;
- (id)_generateSnapshotForWindow:(id)arg1;

@end

