//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSView;

@protocol _NSStepperTrackable <NSObject>
@property BOOL autorepeat;
@property(getter=isHighlighted) BOOL highlighted;
- (BOOL)_sendActionFrom:(NSView *)arg1;
@end

