//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSScreenConfiguration : NSObject
{
}

+ (double)latestGreatestBackingScaleFactor;
+ (BOOL)latestZeroScreenIsNew;
+ (double)latestZeroScreenHeight;
+ (id)latestScreens;
+ (BOOL)invalidateConfigurationIfNeededForReason:(unsigned long long)arg1;
+ (void)invalidateConfigurationForReason:(unsigned long long)arg1;
+ (void)prepare;

@end

