//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _NSScrollingScoreKeeper : NSObject
{
}

+ (void)playScrollRecordingData:(id)arg1 atWindow:(id)arg2 location:(struct CGPoint)arg3 completionHandler:(CDUnknownBlockType)arg4;
+ (id)scrollRecordingDataFromEventArray:(id)arg1;

@end

