//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScrubberSelectionStyle.h>

__attribute__((visibility("hidden")))
@interface _NSScrubberViewClassSelectionStyle : NSScrubberSelectionStyle
{
    Class _viewClass;
}

- (id)makeSelectionView;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithViewClass:(Class)arg1;

@end

