//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableSet;

__attribute__((visibility("hidden")))
@interface _NSServiceRequestorInfo : NSObject
{
    id requestor;
    NSMutableSet *sendTypes;
    NSMutableArray *serviceEntries;
}

- (void)dealloc;
- (id)initWithRequestor:(id)arg1;

@end

