//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSSavePanelCustomAction;

@protocol _NSSavePanelCommonIPI <NSObject>
- (void)_customActionChanged:(NSSavePanelCustomAction *)arg1;
@end

