//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSColor, NSMutableDictionary, NSSliderAccessory, NSTimer;
@protocol NSSliderCellMetricsStrategy;

__attribute__((visibility("hidden")))
@interface _NSSliderCellPrivateData : NSObject
{
    NSMutableDictionary *_tickMarkProminence;
    double originalValue;
    double defaultValue;
    long long trackingPressureStage;
    NSSliderAccessory *minimumValueAccessory;
    NSSliderAccessory *maximumValueAccessory;
    id <NSSliderCellMetricsStrategy> metricsStrategy;
    NSTimer *repeatTimer;
    NSColor *_trackFillColor;
}

@property(copy) NSColor *trackFillColor; // @synthesize trackFillColor=_trackFillColor;
- (void)dealloc;
@property(copy) NSMutableDictionary *tickMarkProminence;

@end

