//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface _NSSoundAux : NSObject
{
    NSString *audioDeviceUID;
    NSArray *channelMapping;
    float _volume;
    unsigned char _ivarFlags;
    unsigned int _systemSoundID;
}

@end

