//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSColor, NSVisualEffectView;

__attribute__((visibility("hidden")))
@interface _NSScrollViewContentBackgroundView : NSView
{
    NSColor *_backgroundColor;
    NSVisualEffectView *_visualEffectView;
}

- (void)dealloc;
- (void)layout;
- (void)updateLayer;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)wantsUpdateLayer;
@property(retain) NSColor *backgroundColor;

@end

