//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol _NSScrollStateEventListener <NSObject>
- (void)scrollStateEvent:(long long)arg1 sender:(id)arg2;
@end

