//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageRep.h>

__attribute__((visibility("hidden")))
@interface _NSSVGImageRep : NSImageRep
{
    struct CGSVGDocument *_document;
}

- (void)dealloc;
- (BOOL)draw;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSVGDocument:(struct CGSVGDocument *)arg1;
- (id)initWithData:(id)arg1;

@end

