//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSegmentItemView;

__attribute__((visibility("hidden")))
@interface _NSSegmentItemAuxiliary : NSObject
{
    long long _index;
    NSSegmentItemView *_segmentItemView;
}

@property(retain) NSSegmentItemView *segmentItemView; // @synthesize segmentItemView=_segmentItemView;
@property long long index; // @synthesize index=_index;
- (void)dealloc;

@end

