//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSBundle, NSDictionary, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface _NSStoryboardPrivateData : NSObject
{
    NSBundle *bundle;
    NSString *storyboardFileName;
    NSDictionary *identifierToNibNameMap;
    NSDictionary *identifierToExternalStoryboardReferenceMap;
    NSDictionary *identifierToUUIDMap;
    NSString *designatedEntryPointIdentifier;
    NSMutableDictionary *identifierToUINibMap;
    NSString *mainMenu;
    NSArray *topLevelObjects;
    NSBundle *ownerBundle;
}

- (void)dealloc;

@end

