//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSTextFieldPlugin.h>

__attribute__((visibility("hidden")))
@interface _NSSearchFieldPlugin : _NSTextFieldPlugin
{
}

- (unsigned long long)allowedValueBindingMask;
- (BOOL)needsAction;

@end

