//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScrubberSelectionStyle.h>

__attribute__((visibility("hidden")))
@interface _NSScrubberOutlineSelectionStyle : NSScrubberSelectionStyle
{
    BOOL _showsHighlight;
}

@property BOOL showsHighlight; // @synthesize showsHighlight=_showsHighlight;
- (id)makeSelectionView;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

