//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _NSTextFinderAttributedStringProxy : NSAttributedString
{
    NSString *_string;
}

- (struct _NSRange)doubleClickAtIndex:(unsigned long long)arg1;
- (id)attributesAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (id)string;
- (void)dealloc;
- (id)initWithString:(id)arg1;

@end

