//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSObjectAnimator.h>

__attribute__((visibility("hidden")))
@interface _NSTitlebarAccessoryAnimator : _NSObjectAnimator
{
}

- (void)setHidden:(BOOL)arg1;

@end

