//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSTrackingRegionKey : NSObject
{
    long long _trackingID;
    unsigned int _windowID;
}

- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithTrackingID:(long long)arg1 windowID:(unsigned int)arg2;

@end

