//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSortDescriptor, NSString, _NSBindingAdaptor;

__attribute__((visibility("hidden")))
@interface _NSTableColumnAuxiliary : NSObject
{
    NSSortDescriptor *_sortDescriptorPrototype;
    _NSBindingAdaptor *_bindingAdaptor;
    NSString *_headerToolTip;
    CDStruct_6b6ad735 _cachedPosition;
}

- (void).cxx_destruct;

@end

