//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSToolbarItemViewerAccessibilityHelper.h>

__attribute__((visibility("hidden")))
@interface _NSToolbarViewItemViewerAccessibilityHelper : _NSToolbarItemViewerAccessibilityHelper
{
}

- (BOOL)accessibilityIsIgnored;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)accessibilityRoleAttribute;

@end

