//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopoverTouchBarItem.h>

@class NSButtonGroupTouchBarItem;

__attribute__((visibility("hidden")))
@interface _NSTouchBarGroupPopoverBarItem : NSPopoverTouchBarItem
{
    NSButtonGroupTouchBarItem *_groupBarItem;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (void).cxx_destruct;
@property __weak NSButtonGroupTouchBarItem *groupBarItem; // @synthesize groupBarItem=_groupBarItem;
- (BOOL)isVisible;

@end

