//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _NSToolbarItemAuxiliary : NSObject
{
    NSArray *_allPossibleLabelsToFit;
    id _partitionAdapter;
    id _propertyListRepresentation;
    long long _visibilityPriority;
    double _preferredWidthRatio;
}

- (void)dealloc;

@end

