//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSEvent;

__attribute__((visibility("hidden")))
@interface _NSTableViewDelayProxy : NSObject
{
    long long column;
    NSEvent *event;
    long long row;
}

+ (id)proxy;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;

@end

