//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSViewAnimator.h>

__attribute__((visibility("hidden")))
@interface _NSTableViewAnimator : _NSViewAnimator
{
}

- (void)selectRowIndexes:(id)arg1 byExtendingSelection:(BOOL)arg2;

@end

