//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSToolbarItem.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface _NSToolbarExternalDragItem : NSToolbarItem
{
    NSArray *externalItems;
}

@property(copy, nonatomic) NSArray *externalItems; // @synthesize externalItems;
- (void)dealloc;

@end

