//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NS1DVelocityFilter.h>

__attribute__((visibility("hidden")))
@interface _NSTableRowSwipeVelocityFilter : _NS1DVelocityFilter
{
    long long _filterDepth;
    double _lastDeltaInput;
    BOOL _isBufferFull;
    long long _bufferIndex;
    double _deltaBuffer[3];
    double _timeBuffer[3];
}

- (void)reset;
- (void)addDelta:(double)arg1 withTimestamp:(double)arg2;
- (double)filteredVelocity;
- (id)init;

@end

