//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol _NSTouchBarItemLayoutWrapper <NSObject>
@property(readonly) BOOL isSpace;
@property(readonly) struct CGSize maxSize;
@property(readonly) struct CGSize minSize;

@optional
@property(readonly) BOOL participatesInOverflow;
@property(readonly) double preferredTrailingPosition;
@property(readonly) double preferredZOrder;
@property(readonly) unsigned long long itemPosition;
@property(readonly) long long priorityIndex;
@property(readonly) struct CGSize contentClippingSize;
@property(readonly) struct CGSize preferredSize;
- (struct CGSize)sizeThatFitsProposedLayoutSize:(struct CGSize)arg1;
@end

