//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSBinderPlugin-Protocol.h>

@protocol _NSTextColorBinderPlugin <_NSBinderPlugin>
- (id)textColorInvalidationCapableObjectForObject:(id)arg1;
@end

