//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSPanel;

__attribute__((visibility("hidden")))
@interface _NSToolbarConfigPanelLoader : NSObject
{
    NSPanel *panel;
}

+ (id)loadPanelNamed:(id)arg1;
- (id)panel;

@end

