//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSThemeWidgetCell.h>

__attribute__((visibility("hidden")))
@interface _NSThemeCloseWidgetCell : _NSThemeWidgetCell
{
    BOOL _edited;
}

- (BOOL)setEditedFlag:(BOOL)arg1;
- (BOOL)isEdited;
- (id)coreUIValue;
- (int)getState:(id)arg1;
- (BOOL)accessibilityIsEditedAttributeSettable;
- (id)accessibilityEditedAttribute;
- (id)accessibilityAttributeNames;

@end

