//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSViewController;

__attribute__((visibility("hidden")))
@interface _NSTabViewItemAuxiliary : NSObject
{
    struct CGSize cachedMinimumLabelSize;
    long long _springLoadingHighlight;
    NSString *_explicitToolTip;
    NSViewController *_viewController;
}

@property(retain) NSViewController *viewController; // @synthesize viewController=_viewController;
@property(copy) NSString *explicitToolTip; // @synthesize explicitToolTip=_explicitToolTip;
- (void)dealloc;

@end

