//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityReparentingProxy.h>

__attribute__((visibility("hidden")))
@interface _NSToolbarSegmentedViewSegmentProxy : NSAccessibilityReparentingProxy
{
}

+ (id)segmentProxyFor:(id)arg1 parent:(id)arg2;
- (id)accessibilitySizeAttribute;
- (id)accessibilityPositionAttribute;
- (BOOL)accessibilityIsDescriptionAttributeSettable;
- (id)accessibilityDescriptionAttribute;
- (id)accessibilityTitleAttribute;
- (id)accessibilityAttributeNames;
- (long long)index;

@end

