//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _NSTrackingRegionData : NSObject
{
    long long trackingID;
    unsigned long long regionID;
    void *userData;
}

@end

