//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSThemeWidget.h>

__attribute__((visibility("hidden")))
@interface _NSThemeCloseWidget : _NSThemeWidget
{
}

+ (id)closeWidgetInView:(id)arg1 withButtonID:(long long)arg2 action:(SEL)arg3;
+ (void)initialize;
- (void)setDocumentEdited:(BOOL)arg1;

@end

