//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSToolbarButtonViewItemViewerAccessibilityHelper.h>

__attribute__((visibility("hidden")))
@interface _NSToolbarSegmentedViewItemViewerAccessibilityHelper : _NSToolbarButtonViewItemViewerAccessibilityHelper
{
}

- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)accessibilityChildrenAttribute;
- (BOOL)showsAccessibilityDescriptionInIconOnlyMode;
- (id)_accessibilityToolbarButtonElement;

@end

