//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSViewAnimator.h>

__attribute__((visibility("hidden")))
@interface _NSViewAnimator_NSScrollView : _NSViewAnimator
{
}

- (void)setMagnification:(double)arg1 centeredAtPoint:(struct CGPoint)arg2;
- (void)magnifyToFitRect:(struct CGRect)arg1;

@end

