//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSRectSet, NSRegion, NSView, _NSDisplayOperation;

__attribute__((visibility("hidden")))
@interface _NSViewDrawOperation : NSOperation
{
    NSView *_view;
    struct CGRect _rect;
    NSRectSet *_rectSet;
    NSRegion *_windowRegion;
    unsigned long long _options;
    _NSDisplayOperation *_owningDisplayOperation;
}

- (void)main;
- (id)view;
- (void)dealloc;
- (id)initWithView:(id)arg1 rect:(struct CGRect)arg2 rectSet:(id)arg3 windowRegion:(id)arg4 options:(unsigned long long)arg5 owningDisplayOperation:(id)arg6;

@end

