//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CAContext, NSArray, NSCGSWindowLayerSurface, NSView, NSWindow;

__attribute__((visibility("hidden")))
@interface _NSViewLayerSurface : NSObject
{
    NSView *_view;
    NSWindow *_window;
    NSCGSWindowLayerSurface *_surface;
    CAContext *_context;
    CAContext *_functionRowContext;
    unsigned long long _viewGeometryObserver;
    NSArray *_windowObservers;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)invalidate;
- (void)update;
- (id)initWithView:(id)arg1;

@end

