//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSViewAnimator.h>

__attribute__((visibility("hidden")))
@interface _NSViewAnimator_NSButton : _NSViewAnimator
{
}

- (void)setBezelColor:(id)arg1;
- (void)setImagePosition:(unsigned long long)arg1;
- (void)setAlternateImage:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setAttributedAlternateTitle:(id)arg1;
- (void)setAttributedTitle:(id)arg1;
- (void)setAlternateTitle:(id)arg1;
- (void)setTitle:(id)arg1;

@end

