//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface _NSWorkspaceVolumeStatusTracker : NSObject
{
    NSURL *_url;
    NSString *_name;
}

- (void)dealloc;

@end

