//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAppearanceContentStyle.h>

__attribute__((visibility("hidden")))
@interface _NSWidgetContentStyle : NSAppearanceContentStyle
{
    long long _styleType;
}

- (int)_backgroundStyleForRenderingIntent:(long long)arg1;
- (void)_configureStyleEffectConfiguration:(id)arg1 forRenderingIntent:(long long)arg2;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithStyleType:(long long)arg1;

@end

