//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSGradient.h>

__attribute__((visibility("hidden")))
@interface _NSWindowBorderGradient : NSGradient
{
}

- (id)initFromGrayValue:(int)arg1 toGrayValue:(int)arg2 colorSpace:(id)arg3;

@end

