//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CABasicAnimation.h>

@interface CABasicAnimation (NSInternal)
- (void)NS_transformValuesAtKeyPath:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)NS_takeImpliedValuesFromPresentationObject:(id)arg1 modelObject:(id)arg2;
@end

