//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CAPropertyAnimation.h>

@interface CAPropertyAnimation (NSInternal)
- (void)NS_addAffectedKeyPaths:(id)arg1;
- (void)NS_renameKeyPathsUsingBlock:(CDUnknownBlockType)arg1;
- (void)NS_renameKeyPath:(id)arg1 toKeyPath:(id)arg2;
@end

