//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol CARenderValue <NSObject>

@optional
- (unsigned long long)CA_copyNumericValue:(double [20])arg1;
- (void *)CA_copyRenderValue;
- (void)CA_prepareRenderValue;
@end

