//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CATransaction.h>

@interface CATransaction (NSCATransaction)
+ (BOOL)NS_tryAggressiveCommit;
+ (void)NS_setFlushesWithDisplayLink;
+ (void)NS_apply:(long long)arg1 block:(CDUnknownBlockType)arg2;
+ (void)NS_setBackground:(BOOL)arg1;
+ (BOOL)NS_isBackground;
@end

