//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CKContainerSetupInfo;

@protocol NS_FIAuthShareInvitationProtocol
- (void)setCKContainerSetupInfo:(CKContainerSetupInfo *)arg1 completionHandler:(void (^)(void))arg2;
@end

