//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityStaticText-Protocol.h>

@class NSString;

@protocol NSAccessibilityNavigableStaticText <NSAccessibilityStaticText>
- (struct CGRect)accessibilityFrameForRange:(struct _NSRange)arg1;
- (struct _NSRange)accessibilityRangeForLine:(long long)arg1;
- (long long)accessibilityLineForIndex:(long long)arg1;
- (NSString *)accessibilityStringForRange:(struct _NSRange)arg1;
@end

