//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityElement-Protocol.h>

@class NSString;

@protocol NSAccessibilityStepper <NSAccessibilityElement>
- (BOOL)accessibilityPerformDecrement;
- (BOOL)accessibilityPerformIncrement;
- (NSString *)accessibilityLabel;

@optional
- (id)accessibilityValue;
@end

