//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityButton-Protocol.h>

@class NSString;

@protocol NSAccessibilitySwitch <NSAccessibilityButton>
- (NSString *)accessibilityValue;

@optional
- (BOOL)accessibilityPerformDecrement;
- (BOOL)accessibilityPerformIncrement;
@end

