//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityGroup-Protocol.h>

@class NSNumber;

@protocol NSAccessibilityProgressIndicator <NSAccessibilityGroup>
- (NSNumber *)accessibilityValue;
@end

