//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityGroup-Protocol.h>

@class NSArray, NSString;

@protocol NSAccessibilityLayoutArea <NSAccessibilityGroup>
@property(readonly) id accessibilityFocusedUIElement;
- (NSArray *)accessibilitySelectedChildren;
- (NSArray *)accessibilityChildren;
- (NSString *)accessibilityLabel;
@end

