//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSData;

@protocol NSAccessibilityCustomElementDataProvider <NSObject>
+ (id)elementWithAccessibilityCustomElementData:(NSData *)arg1;
- (NSData *)accessibilityCustomElementData;

@optional
- (BOOL)overridePresenterPid:(int *)arg1;
- (BOOL)overrideElementPid:(int *)arg1;
@end

