//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityMockUIElement.h>

__attribute__((visibility("hidden")))
@interface NSAccessibilityScrollerPart : NSAccessibilityMockUIElement
{
    unsigned long long _partCode;
}

+ (id)partWithCode:(unsigned long long)arg1 parent:(id)arg2;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (void)accessibilitySetValueAttribute:(id)arg1;
- (BOOL)accessibilityIsValueAttributeSettable;
- (id)accessibilityValueAttribute;
- (id)accessibilityAttributeNames;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)partCode;
- (id)initWithPartCode:(unsigned long long)arg1 parent:(id)arg2;

@end

