//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCell.h>

@interface NSActionCell : NSCell
{
    long long _tag;
    id _target;
    SEL _action;
    id _controlView;
}

+ (void)initialize;
- (id)controlView;
- (void)setControlView:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property long long tag;
@property SEL action;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property __weak id target;
- (void)dealloc;

@end

