//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityTable-Protocol.h>

@protocol NSAccessibilityOutline <NSAccessibilityTable>
@end

