//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAccessibilityCustomChooserItemResult, NSString;

@interface NSAccessibilityCustomChooserSearchPredicate : NSObject
{
    NSAccessibilityCustomChooserItemResult *_currentItem;
    long long _searchDirection;
    NSString *_filterText;
}

@property(copy, nonatomic) NSString *filterText; // @synthesize filterText=_filterText;
@property(nonatomic) long long searchDirection; // @synthesize searchDirection=_searchDirection;
@property(retain, nonatomic) NSAccessibilityCustomChooserItemResult *currentItem; // @synthesize currentItem=_currentItem;
- (void)dealloc;

@end

