//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityElement-Protocol.h>

@class NSString;

@protocol NSAccessibilityButton <NSAccessibilityElement>
- (BOOL)accessibilityPerformPress;
- (NSString *)accessibilityLabel;
@end

