//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityMockUIElement.h>

__attribute__((visibility("hidden")))
@interface NSAccessibilityMenuExtrasMenuBar : NSAccessibilityMockUIElement
{
}

- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)_accessibilityChildren;
- (void)dealloc;
- (BOOL)accessibilityShouldUseUniqueId;

@end

