//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityGroup-Protocol.h>

@protocol NSAccessibilityRow <NSAccessibilityGroup>
- (long long)accessibilityIndex;

@optional
- (long long)accessibilityDisclosureLevel;
@end

