//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityGroup-Protocol.h>

@class NSArray, NSString;

@protocol NSAccessibilityTable <NSAccessibilityGroup>
- (NSArray *)accessibilityRows;
- (NSString *)accessibilityLabel;

@optional
- (NSArray *)accessibilityColumnHeaderUIElements;
- (NSArray *)accessibilityRowHeaderUIElements;
- (NSArray *)accessibilityVisibleCells;
- (NSArray *)accessibilitySelectedCells;
- (NSString *)accessibilityHeaderGroup;
- (NSArray *)accessibilitySelectedColumns;
- (NSArray *)accessibilityVisibleColumns;
- (NSArray *)accessibilityColumns;
- (NSArray *)accessibilityVisibleRows;
- (void)setAccessibilitySelectedRows:(NSArray *)arg1;
- (NSArray *)accessibilitySelectedRows;
@end

