//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityMockUIElement.h>

__attribute__((visibility("hidden")))
@interface NSAccessibilitySliderValueIndicator : NSAccessibilityMockUIElement
{
}

- (void)accessibilitySetValueAttribute:(id)arg1;
- (BOOL)accessibilityIsValueAttributeSettable;
- (id)accessibilityValueAttribute;
- (id)accessibilityAttributeNames;

@end

