//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSAffineTransform.h>

@interface NSAffineTransform (NSAppKitAdditions)
+ (id)transformWithCGAffineTransform:(struct CGAffineTransform)arg1;
- (void)concat;
- (void)set;
- (id)transformBezierPath:(id)arg1;
@property struct CGAffineTransform CGAffineTransform;
@end

