//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDictionary, NSString;

@protocol NSAnimatablePropertyContainer
+ (id)defaultAnimationForKey:(NSString *)arg1;
@property(copy) NSDictionary *animations;
- (id)animationForKey:(NSString *)arg1;
- (id)animator;
@end

