//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSApplication, NSException;

@protocol NSAppExceptionListener <NSObject>
- (void)application:(NSApplication *)arg1 willReportException:(NSException *)arg2 willCrash:(BOOL)arg3 willShow:(BOOL)arg4;
@end

