//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSAppearance;

@protocol NSAppearanceCustomization <NSObject>
@property(readonly) NSAppearance *effectiveAppearance;
@property(retain) NSAppearance *appearance;
@end

