//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAppearanceCustomization-Protocol.h>

@protocol NSAppearanceCustomization;

@protocol NSAppearanceCustomizationInternal <NSAppearanceCustomization>
@property(readonly) id <NSAppearanceCustomization> _effectiveAppearanceParent;
@end

