//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSBuiltinAppearance.h>

__attribute__((visibility("hidden")))
@interface NSAquaAppearance : NSBuiltinAppearance
{
}

- (id)_appearanceForNonVibrantContent;
- (id)_appearanceForVibrantContent;

@end

