//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWeakAutounbinderBinding.h>

__attribute__((visibility("hidden")))
@interface NSAutounbinderBinding : NSWeakAutounbinderBinding
{
}

- (void)dealloc;
- (id)initWithName:(id)arg1 boundObject:(id)arg2;

@end

