//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAutoreleaseContext;

__attribute__((visibility("hidden")))
@interface NSAutoreleaseIdentifier : NSObject
{
    id _receiver;
    NSAutoreleaseContext *_context;
}

@property(readonly) NSAutoreleaseContext *context; // @synthesize context=_context;
@property(readonly) id receiver; // @synthesize receiver=_receiver;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToIdentifier:(id)arg1;
- (void)dealloc;
- (id)initWithReceiver:(id)arg1 context:(id)arg2;

@end

