//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTabBarItem;

__attribute__((visibility("hidden")))
@interface NSBaseTabData : NSObject
{
    NSTabBarItem *_tabBarItem;
}

- (void).cxx_destruct;
@property(retain) NSTabBarItem *tabBarItem; // @synthesize tabBarItem=_tabBarItem;
- (void)dispose;

@end

