//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/NSCopying-Protocol.h>

@interface NSBindingSelectionMarker : NSObject <NSCopying>
{
}

+ (id)defaultPlaceholderForMarker:(id)arg1 onClass:(Class)arg2 withBinding:(id)arg3;
+ (void)setDefaultPlaceholder:(id)arg1 forMarker:(id)arg2 onClass:(Class)arg3 withBinding:(id)arg4;
+ (id)notApplicableSelectionMarker;
+ (id)noSelectionMarker;
+ (id)multipleValuesSelectionMarker;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

