//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAppearance.h>

@class NSBundle, NSString;

__attribute__((visibility("hidden")))
@interface NSBuiltinAppearance : NSAppearance
{
    NSBundle *_systemAppearanceBundle;
    NSString *_publicName;
}

- (id)appearanceByApplyingTintColor:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)_bundleResourceName;
- (BOOL)_isBuiltinAppearance;
- (void)dealloc;
- (id)name;
- (id)initWithBundleResourceName:(id)arg1 publicName:(id)arg2;

@end

