//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

__attribute__((visibility("hidden")))
@interface NSButtonTextFieldCell : NSTextFieldCell
{
}

- (BOOL)_shouldDrawHighlightRect;

@end

