//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWidgetView.h>

__attribute__((visibility("hidden")))
@interface NSButtonBezelView : NSWidgetView
{
}

- (void)setTranslatesAutoresizingMaskIntoConstraints:(BOOL)arg1;
- (int)_vibrancyBlendMode;
- (void)updateLayer;

@end

