//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

__attribute__((visibility("hidden")))
@interface NSButtonTextField : NSTextField
{
}

+ (Class)cellClass;
- (struct NSEdgeInsets)alignmentRectInsets;
- (int)_vibrancyBlendMode;

@end

