//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSSimpleImageView.h>

@class NSImage;

__attribute__((visibility("hidden")))
@interface NSButtonImageView : _NSSimpleImageView
{
    NSImage *_image;
}

+ (id)keyPathsForValuesInvalidatingDisplay;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
- (int)_vibrancyBlendMode;
- (void)dealloc;

@end

