//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSDeviceWhiteColor.h>

__attribute__((visibility("hidden")))
@interface NSCachedDeviceWhiteColor : NSDeviceWhiteColor
{
}

- (BOOL)retainWeakReference;
- (BOOL)allowsWeakReference;
- (id)copy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)autorelease;
- (unsigned long long)retainCount;
- (id)retain;
- (oneway void)release;

@end

