//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAppearance;

__attribute__((visibility("hidden")))
@interface NSCarbonMenuImplExtraVars : NSObject
{
    id customHandlerList;
    struct SLMPopUpMenuContext_t *popUpContext;
    NSAppearance *menuAppearance;
}

- (void)dealloc;

@end

