//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCGSWindowCornerMask.h>

__attribute__((visibility("hidden")))
@interface NSCGSMutableWindowCornerMask : NSCGSWindowCornerMask
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property struct CGRect center; // @dynamic center;
@property(retain) struct CGImage *image; // @dynamic image;
@property double imageScale; // @dynamic imageScale;

@end

