//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSItemProvider.h>

@interface NSCloudKitShareProvider : NSItemProvider
{
}

- (id)initWithPreparationHandler:(CDUnknownBlockType)arg1;
- (id)initWithShare:(id)arg1 container:(id)arg2;

@end

