//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSharingServiceDelegate-Protocol.h>

@class CKShare, NSArray, NSError, NSItemProvider, NSSharingService;

@protocol NSCloudSharingServiceDelegate <NSSharingServiceDelegate>

@optional
- (void)sharingService:(NSSharingService *)arg1 didStopSharing:(CKShare *)arg2;
- (void)sharingService:(NSSharingService *)arg1 didSaveShare:(CKShare *)arg2;
- (unsigned long long)optionsForSharingService:(NSSharingService *)arg1 shareProvider:(NSItemProvider *)arg2;
- (void)sharingService:(NSSharingService *)arg1 didCompleteForItems:(NSArray *)arg2 error:(NSError *)arg3;
@end

