//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityElement.h>

@class NSAccessibilityWeakReferenceContainer, NSCollectionViewSectionAccessibility;

__attribute__((visibility("hidden")))
@interface NSCollectionViewSupplementaryViewAccessibility : NSAccessibilityElement
{
    NSAccessibilityWeakReferenceContainer *_sectionAccessibility;
}

- (id)accessibilityChildren;
- (struct CGRect)accessibilityFrame;
- (id)accessibilityParent;
- (id)accessibilityRole;
- (id)supplementaryView;
@property(readonly, nonatomic) __weak NSCollectionViewSectionAccessibility *sectionAccessibility; // @dynamic sectionAccessibility;
- (void)dealloc;
- (id)initWithSectionAccessibility:(id)arg1;

@end

