//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBar.h>

__attribute__((visibility("hidden")))
@interface NSControlStripTouchBar : NSTouchBar
{
}

- (void)_persistWithItemIdentifiers:(id)arg1 toDomain:(id)arg2;
- (void)_resetCustomization;

@end

