//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSColor, NSColorPickerMatrixView;

@protocol NSColorPickerMatrixViewDelegate <NSObject>

@optional
- (NSColor *)matrixColorPicker:(NSColorPickerMatrixView *)arg1 highlightColorForColor:(NSColor *)arg2;
- (void)matrixColorPicker:(NSColorPickerMatrixView *)arg1 selectedColor:(NSColor *)arg2;
@end

