//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCollectionViewSupplementaryViewAccessibility.h>

__attribute__((visibility("hidden")))
@interface NSCollectionViewHeaderAccessibility : NSCollectionViewSupplementaryViewAccessibility
{
}

- (long long)accessibilityIndex;
- (id)accessibilityNextContentSibling;
- (id)accessibilityPreviousContentSibling;
- (id)supplementaryView;

@end

