//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColor.h>

@interface NSColor (NSUIKitSupport)
+ (void)load;
+ (Class)classForKeyedUnarchiver;
@end

