//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColorPickingDefault-Protocol.h>

@class NSColor, NSView;

@protocol NSColorPickingCustom <NSColorPickingDefault>
- (void)setColor:(NSColor *)arg1;
- (NSView *)provideNewView:(BOOL)arg1;
- (long long)currentMode;
- (BOOL)supportsMode:(long long)arg1;
@end

