//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPanel.h>

__attribute__((visibility("hidden")))
@interface NSCorrectionSubPanel : NSPanel
{
    id _panelAccessibilityParent;
}

@property(retain) id panelAccessibilityParent; // @synthesize panelAccessibilityParent=_panelAccessibilityParent;
- (unsigned long long)shadowOptions;
- (id)accessibilityActionNames;
- (BOOL)accessibilityIsHelpAttributeSettable;
- (id)accessibilityHelpAttribute;
- (BOOL)accessibilityIsWindowAttributeSettable;
- (id)accessibilityWindowAttribute;
- (BOOL)accessibilityIsTopLevelUIElementAttributeSettable;
- (id)accessibilityTopLevelUIElementAttribute;
- (id)accessibilityParentAttribute;
- (id)accessibilityRoleAttribute;
- (id)accessibilityAttributeNames;
- (void)dealloc;

@end

