//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

__attribute__((visibility("hidden")))
@interface NSComboBoxButtonCell : NSButtonCell
{
}

- (void)accessibilityPerformAction:(id)arg1;

@end

