//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBundle, NSString;

__attribute__((visibility("hidden")))
@interface NSColorListAuxiliary : NSObject
{
    NSString *_localizedCopyRightString;
    struct CMNamedColorPageInfoType *_cmPageInfoPtr;
    double _lastEditableCheck;
    NSBundle *_bundleForColorListDirectory;
}

- (void)dealloc;
- (id)init;

@end

