//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCollectionViewSectionAccessibility.h>

__attribute__((visibility("hidden")))
@interface NSCollectionViewFlowLayoutSectionAccessibility : NSCollectionViewSectionAccessibility
{
    id _supplementaryHeaderElement;
    id _supplementaryFooterElement;
}

- (id)accessibilityLabel;
- (BOOL)hasSupplementaryFooterView;
- (BOOL)hasSupplementaryHeaderView;
- (id)supplementaryFooterView:(BOOL)arg1;
- (id)supplementaryHeaderView:(BOOL)arg1;
- (id)_makeSupplementaryFooterView;
- (id)_makeSupplementaryHeaderView;
- (id)supplementaryFooterElement;
- (id)supplementaryHeaderElement;
- (BOOL)_hasSupplementaryViewForElementKind:(id)arg1;
- (BOOL)__hasSupplementaryViewForSelector:(SEL)arg1 sizeDelegateBlock:(CDUnknownBlockType)arg2 sizeNoDelegateBlock:(CDUnknownBlockType)arg3;

@end

