//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableView.h>

__attribute__((visibility("hidden")))
@interface NSComboTableView : NSTableView
{
    long long _lastReturnedNumberOfRows;
}

+ (BOOL)_logErrorForNonStringIdentifier;
- (BOOL)_shouldBlurSelectionWhenCellBased;
- (id)initWithCoder:(id)arg1;
- (long long)numberOfRows;
- (BOOL)shouldDelayWindowOrderingForEvent:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)_accessibilityWantsToBeList;

@end

