//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColorPickingCustom-Protocol.h>

@class NSString;

@protocol NSColorPickingInternal <NSColorPickingCustom>
@property(readonly, copy) NSString *pickerIdentifier;
@property BOOL isActivePicker;
@end

