//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSCoder.h>

@interface NSCoder (NSIBDependencyInjectionInternal)
- (void)_replaceClassSwapperWithViewController:(id)arg1;
- (id)decodeNXColor;
- (int)_decodeDepth;
- (void)_encodeDepth:(int)arg1;
- (unsigned char)_decodeByte;
- (void)_encodeByte:(unsigned char)arg1;
@end

