//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/NSCoding-Protocol.h>

@class NSString;

@interface NSCustomObject : NSObject <NSCoding>
{
    NSString *className;
    id object;
    id extension;
}

+ (void)initialize;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setClassName:(id)arg1;
- (id)className;
- (void)setObject:(id)arg1;
- (id)nibInstantiate;
- (void)dealloc;
- (id)init;

@end

