//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSMenu.h>

__attribute__((visibility("hidden")))
@interface NSDataDetectionIndicatorMenu : NSMenu
{
    id _delegate;
}

- (void)performActionForItemAtIndex:(long long)arg1;
- (void)setDelegate:(id)arg1;

@end

