//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSArray;

@protocol NSDebugTouchBarUIDelegate <NSObject>
- (void)didUpdateResponderChainItems:(NSArray *)arg1;
@end

