//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSDynamicNamedColor.h>

__attribute__((visibility("hidden")))
@interface NSDecodedCustomDynamicColor : NSDynamicNamedColor
{
}

- (id)colorWithAlphaComponent:(double)arg1;
- (id)resolvedColor;
- (Class)classForCoder;

@end

