//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSMenuItem;

@protocol NSDebugMenuItemProvider <NSObject>
@property(readonly, copy) NSMenuItem *menuItem;
- (id)init;
@end

