//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSGridView;

__attribute__((visibility("hidden")))
@interface NSDebugTouchBarItemInspectorViewController : NSViewController
{
    NSGridView *_gridView;
}

- (void)setRepresentedObject:(id)arg1;
- (void)dealloc;
- (void)loadView;

@end

