//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSGridView, NSImageView, NSPopover;

__attribute__((visibility("hidden")))
@interface NSDebugTouchBarInspectorViewController : NSViewController
{
    NSImageView *_imageView;
    NSGridView *_gridView;
    NSPopover *_inspectorPopover;
}

- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)dealloc;
- (void)loadView;

@end

