//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSDetachedTabDraggingImageToWindowTransitionController, NSWindow;

@protocol NSDetachedTabDraggingImageToWindowTransitionControllerDelegate <NSObject>
- (void)detachedTabDraggingImageToWindowTransitionController:(NSDetachedTabDraggingImageToWindowTransitionController *)arg1 didFinishTransitionAnimationForWindow:(NSWindow *)arg2;
- (NSWindow *)destinationWindowForDetachedTabDraggingImageToWindowTransitionController:(NSDetachedTabDraggingImageToWindowTransitionController *)arg1;
- (BOOL)destinationWindowShouldMoveToDropPointInSpace:(unsigned long long)arg1 forDetachedTabDraggingImageToWindowTransitionController:(NSDetachedTabDraggingImageToWindowTransitionController *)arg2;
@end

