//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface NSDictionaryControllerKeyValuePair : NSObject
{
}

@property(readonly, getter=isExplicitlyIncluded) BOOL explicitlyIncluded; // @dynamic explicitlyIncluded;
@property(retain) id value; // @dynamic value;
@property(copy) NSString *key; // @dynamic key;
@property(copy) NSString *localizedKey; // @dynamic localizedKey;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)_init;
- (id)init;

@end

