//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSDisplayLink : NSObject
{
}

+ (double)currentTimestamp;
@property(getter=isPaused) BOOL paused;
- (void)invalidate;
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;
- (void)addToRunLoop:(id)arg1 forMode:(id)arg2;
@property BOOL executesConcurrently;

@end

