//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

__attribute__((visibility("hidden")))
@interface NSDocumentRevisionsRevertProgressOverlayWindow : NSWindow
{
}

- (BOOL)canBecomeKeyWindow;
- (void)_orderOutRelativeToWindow:(id)arg1;
- (void)_orderFrontRelativeToWindow:(id)arg1;

@end

