//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAppearance.h>

__attribute__((visibility("hidden")))
@interface NSDocumentRevisionsButtonAppearance : NSAppearance
{
}

- (BOOL)allowsVibrancy;
- (id)init;

@end

