//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

__attribute__((visibility("hidden")))
@interface NSDocumentRevisionsAuxiliaryWindow : NSWindow
{
    id _customAccessibilityParent;
}

- (void).cxx_destruct;
@property __weak id customAccessibilityParent; // @synthesize customAccessibilityParent=_customAccessibilityParent;
- (id)accessibilityParentAttribute;
- (id)accessibilityChildrenAttribute;
- (BOOL)_shouldAutoFlattenLayerTree;
- (BOOL)accessibilityIsIgnored;

@end

