//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class CABackdropLayer;

__attribute__((visibility("hidden")))
@interface NSDocumentRevisionsStackLayer : CALayer
{
    CABackdropLayer *backdropLayer;
}

@property(retain) CABackdropLayer *backdropLayer; // @synthesize backdropLayer;
- (struct CGPoint)anchorPoint;
- (void)setAnchorPoint:(struct CGPoint)arg1;
- (void)dealloc;

@end

