//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCoding-Protocol.h>
#import <AppKit/NSCopying-Protocol.h>
#import <AppKit/NSObject-Protocol.h>

@class NSColor;

@protocol NSDynamicColorModifier <NSObject, NSCopying, NSCoding>
- (NSColor *)colorByApplyingToColor:(NSColor *)arg1;
@end

