//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSKeyValueDependencyInfo, NSObject, NSString;

@protocol NSDynamicPropertyContainer <NSObject>
+ (BOOL)automaticallyTracksDependenciesOnValueForKey:(NSString *)arg1;
@property(readonly) BOOL _isDeallocating;
@property(retain) NSKeyValueDependencyInfo *dependencyInfo;
- (void)removeObserver:(NSObject *)arg1 forKeyPath:(NSString *)arg2 context:(void *)arg3;
- (void)addObserver:(NSObject *)arg1 forKeyPath:(NSString *)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
@end

