//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSEditor;

@protocol NSEditorRegistration <NSObject>

@optional
- (void)objectDidEndEditing:(id <NSEditor>)arg1;
- (void)objectDidBeginEditing:(id <NSEditor>)arg1;
@end

