//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSSpellCheckingResult.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface NSExtendedSpellCheckingResult : NSSpellCheckingResult
{
    struct _NSRange _sentenceRange;
    NSDictionary *_detail;
}

- (BOOL)isSentenceCorrectionResult;
- (id)detail;
- (struct _NSRange)sentenceRange;
- (void)dealloc;
- (id)initWithRange:(struct _NSRange)arg1 sentenceRange:(struct _NSRange)arg2 detail:(id)arg3;

@end

