//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSExtension.h>

@interface NSExtension (NSExtension_AppKitAdditions)
+ (unsigned long long)numberOfNewItems;
+ (void)initialize;
@end

