//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

__attribute__((visibility("hidden")))
@interface NSFakePopoverBackgroundView : NSVisualEffectView
{
}

- (id)initWithCoder:(id)arg1;

@end

