//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface NSFileDragSource : NSObject
{
}

+ (unsigned long long)draggingSourceOperationMaskForLocal:(BOOL)arg1;

@end

