//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSFileWrapper.h>

@class NSImage;

@interface NSFileWrapper (NSExtensions)
- (id)_iconData;
- (BOOL)_hasIcon;
- (void)_initIconWithData:(id)arg1;
- (void)_initIcon:(id)arg1;
@property(retain) NSImage *icon;
@end

