//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSFlippableView : NSView
{
}

+ (id)newFlipped:(BOOL)arg1;

@end

