//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColorWell.h>

__attribute__((visibility("hidden")))
@interface NSFontOptionsColorWell : NSColorWell
{
}

- (id)_takeColorFrom:(id)arg1 andSendAction:(BOOL)arg2;

@end

