//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

__attribute__((visibility("hidden")))
@interface NSFontPanelColorWellButtonCell : NSButtonCell
{
}

- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;

@end

