//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIFoundation/NSFont.h>

@interface NSFont (NSPortCoding)
- (id)replacementObjectForPortCoder:(id)arg1;
- (double)_trackingNecessaryToScaleToFontOfSize:(double)arg1;
@property(readonly) double _spaceGlyphAdvance;
@end

