//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NSFontOptionsAttributeDescriptor : NSObject
{
    NSString *_name;
    Class _allowedClass;
}

+ (id)attributeDescriptorWithName:(id)arg1 allowedClass:(Class)arg2;
@property(readonly, nonatomic) Class allowedClass; // @synthesize allowedClass=_allowedClass;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void)dealloc;
- (id)initWithName:(id)arg1 allowedClass:(Class)arg2;

@end

