//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface NSFrontmostDocumentWindowObserver : NSObject
{
}

+ (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
+ (void)window:(id)arg1 didChangeRepresentedURLFromURL:(id)arg2 toURL:(id)arg3;
+ (void)_mainWindowOrURLsDidChange;
+ (void)registerForInterestedFileProviders;

@end

