//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSBuiltinAppearance.h>

__attribute__((visibility("hidden")))
@interface NSFunctionRowAppearance : NSBuiltinAppearance
{
}

- (BOOL)_isFunctionRowAppearance;
- (BOOL)_prefersSliderAccessoryStepBehavior;
- (BOOL)_prefersButtonTitleNaturalBaseline;
- (BOOL)_prefersMoreHorizontalContentIndicators;
- (BOOL)_optionsMustContainTintColor;
- (id)_bundleResourceName;
- (BOOL)_backstoppedByFullAppearance;

@end

