//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTouchDevice;

__attribute__((visibility("hidden")))
@interface NSFunctionRowDevice : NSObject
{
}

+ (BOOL)deviceDimmed;
+ (id)defaultFunctionRowDevice;
+ (id)functionRowDevices;
+ (void)initialize;
@property(readonly) NSTouchDevice *touchDevice;
@property(readonly) struct CGRect frame;

@end

