//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface NSGestureRecognizerTarget : NSObject
{
    id _target;
    SEL _action;
}

- (void).cxx_destruct;
@property SEL action; // @synthesize action=_action;
@property __weak id target; // @synthesize target=_target;
- (id)description;

@end

