//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface NSGlobalPreferenceTransition : NSObject
{
    long long _overlaySpaceID;
    NSArray *_overlays;
    CDUnknownBlockType _completionHandler;
}

+ (id)transition;
- (void)waitForTransitionWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)postChangeNotification:(unsigned long long)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_invalidate;
- (void)dealloc;
- (id)initTransition;

@end

