//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopoverTouchBarItem.h>

__attribute__((visibility("hidden")))
@interface NSHackyPopoverTouchBarItem : NSPopoverTouchBarItem
{
    unsigned int _visible:1;
}

@property(getter=isVisible) BOOL visible;

@end

