//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSHapticFeedbackManager : NSObject
{
}

+ (void)_requestVisuallySynchronizedPerformance:(id)arg1 feedbackPattern:(long long)arg2;
+ (id)defaultPerformer;

@end

