//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSHapticFeedbackPerformer <NSObject>
- (void)performFeedbackPattern:(long long)arg1 performanceTime:(unsigned long long)arg2;
@end

