//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIFoundation/NSTextAttachment.h>

@class NSString;

@interface NSHelpAttachment : NSTextAttachment
{
    NSString *markerName;
    NSString *fileName;
}

- (void)dealloc;
- (id)fileName;
- (id)markerName;
- (id)initWithFileName:(id)arg1 markerName:(id)arg2;

@end

