//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface NSHIPresentationInstance : NSObject
{
    unsigned long long _spaceID;
    struct OpaqueHIPresentationInstanceRef *_ref;
}

- (struct OpaqueHIPresentationInstanceRef *)currentPresentationInstance;
- (void)setSpace:(unsigned long long)arg1;
- (void)discard;
- (id)init;
- (void)dealloc;

@end

