//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageView.h>

__attribute__((visibility("hidden")))
@interface NSImageViewWithWritableAlignmentRectInsets : NSImageView
{
    struct NSEdgeInsets _insets;
}

@property struct NSEdgeInsets alignmentRectInsets; // @synthesize alignmentRectInsets=_insets;

@end

