//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/NSCopying-Protocol.h>

@class NSArray, NSURL;

__attribute__((visibility("hidden")))
@interface NSImageURLReferencingRepProvider : NSObject <NSCopying>
{
    NSURL *_url;
    NSArray *_representations;
}

@property(readonly) NSURL *url; // @synthesize url=_url;
@property(readonly) NSArray *representations;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithURL:(id)arg1;

@end

