//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSInspectorBar, NSString, NSView;
@protocol NSInspectorBarItemController;

@interface NSInspectorBarItem : NSObject
{
    NSString *_identifier;
    NSInspectorBar *_inspectorBar;
    id <NSInspectorBarItemController> _controller;
}

+ (id)separatorItem;
@property(readonly) NSInspectorBar *inspectorBar; // @synthesize inspectorBar=_inspectorBar;
@property(readonly) id <NSInspectorBarItemController> controller; // @synthesize controller=_controller;
- (void)_setInspectorBar:(id)arg1;
@property(readonly) BOOL canBeDetached;
@property(readonly) NSView *view; // @dynamic view;
@property(readonly) NSString *identifier;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1 controller:(id)arg2;

@end

