//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSInputFeedbackPerformer <NSObject>
- (void)performFeedbackPattern:(long long)arg1 forTimestamp:(double)arg2;
@end

