//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol NSInputServerMouseTracker
- (void)mouseUpOnCharacterIndex:(unsigned long long)arg1 atCoordinate:(struct CGPoint)arg2 withModifier:(unsigned long long)arg3 client:(id)arg4;
- (BOOL)mouseDraggedOnCharacterIndex:(unsigned long long)arg1 atCoordinate:(struct CGPoint)arg2 withModifier:(unsigned long long)arg3 client:(id)arg4;
- (BOOL)mouseDownOnCharacterIndex:(unsigned long long)arg1 atCoordinate:(struct CGPoint)arg2 withModifier:(unsigned long long)arg3 client:(id)arg4;
@end

