//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSIndexPath.h>

@interface NSIndexPath (NSBrowserIndexPath)
+ (id)parentIndexPathForIndexPaths:(id)arg1;
- (id)_safeIndexPathByRemovingLastIndex;
- (BOOL)descendsFrom:(id)arg1;
@end

