//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSInputAlignmentGuide, NSInputAlignmentItem;

@protocol NSInputAlignmentMatch <NSObject>
- (id <NSInputAlignmentGuide>)alignmentGuide;
- (id <NSInputAlignmentGuide>)itemRepresentativeGuide;
- (id <NSInputAlignmentItem>)item;
@end

