//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IOSurface, NSDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface NSIOSurfacePool : NSObject
{
    NSDictionary *_surfaceProperties;
    NSMutableArray *_surfaces;
}

@property(readonly) IOSurface *nextUnusedSurface;
@property(readonly, copy) NSDictionary *surfaceProperties;
- (void)dealloc;
- (id)initWithSurfaceProperties:(id)arg1;
- (id)init;

@end

