//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCache;

__attribute__((visibility("hidden")))
@interface NSLayerContentsProvider : NSObject
{
    NSCache *_cache;
}

+ (void)resetCache;
+ (id)sharedContentsProvider;
- (double)totalCacheSize;
- (id)facetForIdentifier:(id)arg1 scale:(double)arg2 colorSpace:(id)arg3 drawingRect:(struct CGRect)arg4 flipped:(BOOL)arg5 appearanceIdentifier:(id)arg6 drawHandler:(CDUnknownBlockType)arg7;
- (void)dealloc;

@end

