//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSBrowserCell.h>

__attribute__((visibility("hidden")))
@interface NSLazyBrowserCell : NSBrowserCell
{
}

+ (id)lazyBrowserCell;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (void)setControlView:(id)arg1;
- (BOOL)_isLoaded;
- (BOOL)isLoaded;
- (void)setLoaded:(BOOL)arg1;
- (void)_clearMouseTracking;
- (void)dealloc;
- (unsigned long long)retainCount;
- (oneway void)release;
- (id)retain;
- (id)init;

@end

