//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage;

__attribute__((visibility("hidden")))
@interface NSLayerContentsFacet : NSObject
{
    id _contents;
    struct CGRect _contentsCenter;
    double _contentsScale;
    struct CGRect _drawingRect;
    NSImage *_image;
}

@property(retain) NSImage *image; // @synthesize image=_image;
@property struct CGRect drawingRect; // @synthesize drawingRect=_drawingRect;
@property double contentsScale; // @synthesize contentsScale=_contentsScale;
@property struct CGRect contentsCenter; // @synthesize contentsCenter=_contentsCenter;
@property(retain) id contents; // @synthesize contents=_contents;
- (double)totalSize;
- (void)dropToImage;
- (void)dealloc;

@end

