//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSLayoutAnchor.h>

@interface NSLayoutAnchor (MidpointAnchor)
- (id)_anchorAtMidpointToAnchor:(id)arg1;
@end

