//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSInputServer.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface NSLocalInputServer : NSInputServer
{
    NSMutableDictionary *_dictionary;
}

- (id)mutableDictionary;
- (void)setMutableDictionary:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 name:(id)arg2;

@end

