//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSLockoutUIWindow-Protocol.h>

@class NSWindow;

@protocol NSLockoutUIOverlayWindow <NSLockoutUIWindow>
- (void)originalDidOrder:(long long)arg1;
- (NSWindow *)original;
@end

