//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSLockoutUIWindow <NSObject>
- (void)disengageWithDuration:(double)arg1 completionHandler:(void (^)(void))arg2;
- (void)engageWithDuration:(double)arg1 completionHandler:(void (^)(void))arg2;
- (BOOL)transitioning;
- (BOOL)engaged;
- (BOOL)isMiniaturized;
@end

