//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSGestureRecognizer.h>

@interface NSLongClickGestureRecognizer : NSGestureRecognizer
{
}

@property double allowableMovement;
@property double minimumPressDuration;
@property unsigned long long buttonMask;

@end

