//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface NSLSNotificationHelper : NSObject
{
}

- (BOOL)isNonEmpty;
- (BOOL)removeEntryAndReturnIfEmpty:(id)arg1;
- (BOOL)addEntryAndReturnIfWasEmpty:(id)arg1;
- (id)init;

@end

