//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSLSNotificationHelper.h>

__attribute__((visibility("hidden")))
@interface NSLSNotificationHelperCountedSet : NSLSNotificationHelper
{
    struct __CFDictionary *_dictionary;
}

- (void)dealloc;
- (BOOL)isNonEmpty;
- (BOOL)removeEntryAndReturnIfEmpty:(id)arg1;
- (BOOL)addEntryAndReturnIfWasEmpty:(id)arg1;

@end

