//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPortDelegate-Protocol.h>

@protocol NSMachPortDelegate <NSPortDelegate>

@optional
- (void)handleMachMessage:(void *)arg1;
@end

