//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSImage, NSMenu, NSString;

@protocol NSMenuToolbarItemControl
@property SEL action;
@property __weak id target;
@property BOOL showsIndicator;
@property(retain) NSMenu *menu;
@property(copy) NSString *title;
@property(retain) NSImage *image;
@end

