//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewTextAttachmentCell.h>

@interface NSMovieViewTextAttachmentCell : NSViewTextAttachmentCell
{
}

- (id)initWithMovie:(id)arg1;

@end

