//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSMorphingDragImageController, NSWindow;

@protocol NSMorphingDragImageControllerDragSource <NSObject>

@optional
- (NSWindow *)dragDestinationWindowForMorphingDragImage:(NSMorphingDragImageController *)arg1;
- (void)morphingDragImage:(NSMorphingDragImageController *)arg1 wasDroppedAtPointOnScreen:(struct CGPoint)arg2;
- (void)morphingDragImage:(NSMorphingDragImageController *)arg1 movedToPointOnScreen:(struct CGPoint)arg2;
@end

