//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSelectionBinder.h>

__attribute__((visibility("hidden")))
@interface NSMultipleSelectionBinder : NSSelectionBinder
{
}

+ (id)bindingCategory;
+ (id)_pluginProtocol;
- (id)_referenceBinding;
- (id)availableBindings;
- (BOOL)insertsNullPlaceholder;
- (id)_optionsForBinding:(id)arg1 specifyOnlyIfDifferentFromDefault:(BOOL)arg2;

@end

