//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableSet.h>

@interface NSMutableSet (NSPasteboardTypesAdditions)
+ (id)_newUniformTypeIdentifierSet;
+ (id)setWithCollectionViewIndexPaths:(id)arg1;
+ (id)setWithCollectionViewIndexPath:(id)arg1;
@end

