//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface NSNavFlippedView : NSView
{
}

- (BOOL)isFlipped;
- (void)awakeFromNib;

@end

