//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/NSCoding-Protocol.h>

@class NSString;

@interface NSNibConnector : NSObject <NSCoding>
{
    id _source;
    id _destination;
    NSString *_label;
}

+ (void)initialize;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)instantiateWithObjectInstantiator:(id)arg1;
- (void)establishConnection;
- (void)replaceObject:(id)arg1 withObject:(id)arg2;
@property(copy) NSString *label;
@property id destination;
@property id source;
- (void)dealloc;
- (id)init;

@end

