//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSNibConnector.h>

@class NSString;

@interface NSNibOutletConnector : NSNibConnector
{
    NSString *_childControllerCreationSelectorName;
}

+ (void)initialize;
- (void)establishConnection;
- (BOOL)_shouldUseSelector:(SEL)arg1 forOutlet:(id)arg2 source:(id)arg3;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

