//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSNotificationCenter.h>

@interface NSNotificationCenter (AppKitAdditions)
- (void)_removeObserver:(id)arg1 notificationNamesAndSelectors:(id)arg2 object:(id)arg3;
- (void)_addObserver:(id)arg1 notificationNamesAndSelectors:(id)arg2 object:(id)arg3;
- (void)_removeObserver:(id)arg1 notificationNamesAndSelectorNames:(id)arg2 object:(id)arg3;
- (void)_addObserver:(id)arg1 notificationNamesAndSelectorNames:(id)arg2 object:(id)arg3 onlyIfSelectorIsImplemented:(BOOL)arg4;
@end

