//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray;

@protocol NSOpenAndSavePanelServiceExportedToRemoteViewProtocol
- (void)retryAfterPresentingError;
- (void)spi_setCustomActions:(NSArray *)arg1;
- (void)setRemoteAccessoryViewDesiredSize:(struct CGSize)arg1;
- (void)validateVisibleColumns;
@end

