//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarItem.h>

@interface NSOtherItemsProxyTouchBarItem : NSTouchBarItem
{
}

- (long long)_type;

@end

