//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSView;

@protocol NSOutlineViewInlineOutlineCell <NSObject>
@property struct CGRect outlineCellFrame;
- (void)updateOutlineCellFrame:(struct CGRect *)arg1 withCellFrame:(struct CGRect)arg2 inView:(NSView *)arg3;
@end

