//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOutlineView;

__attribute__((visibility("hidden")))
@interface NSOVTrackingAreaOwner : NSObject
{
    NSOutlineView *_owner;
}

@property(nonatomic) NSOutlineView *owner; // @synthesize owner=_owner;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;

@end

