//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

__attribute__((visibility("hidden")))
@interface NSOVWrapperButton : NSButton
{
}

- (BOOL)allowsVibrancy;
- (int)_trackingAreasDirty;
- (void)setBackgroundStyle:(long long)arg1;

@end

