//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSPathComponentCell;

__attribute__((visibility("hidden")))
@interface NSPathControlAuxiliary : NSObject
{
    unsigned long long _dropOperation;
    NSPathComponentCell *_dropCell;
}

@property unsigned long long dropOperation; // @synthesize dropOperation=_dropOperation;
@property(retain) NSPathComponentCell *dropCell; // @synthesize dropCell=_dropCell;
- (void)dealloc;

@end

