//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface NSPersistentUIWindowInfo : NSObject
{
    unsigned int windowID;
    int currentStatus;
    unsigned int currentGeneration;
    unsigned char recordEncryptionKey[16];
    NSDictionary *externalPublicProperties;
}

- (const char *)recordEncryptionKey;
- (void)dealloc;
- (id)init;
- (id)copyAllPublicProperties;
- (void)setExternalPublicProperties:(id)arg1;
- (BOOL)isGlobal;
@property unsigned int windowID;

@end

