//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface NSPersistentUISecureURLHerder : NSObject
{
    NSMutableDictionary *_urlsStashedInLSToSharedFileListItemRefs;
    void *_lsSharedFileList;
    NSString *_bundleID;
}

- (void)resolveSecurityScopedURLsFromRecords:(id)arg1;
- (void)fetchAndConsumeLSPersistentFileList;
- (struct OpaqueLSSharedFileListRef *)getLSPersistentFileList;
- (void)dealloc;
- (id)initWithBundleID:(id)arg1;

@end

