//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface NSPersistentUIPreservedStateDirectory : NSObject
{
    NSArray *publicWindowDictionaries;
    int privateStateFD;
}

- (void)dealloc;
- (void)dispose;
- (BOOL)isValid;
- (BOOL)readRecordsIntoArray:(id)arg1 includeCarbonWindows:(BOOL)arg2 includeCocoaWindows:(BOOL)arg3;
- (id)initWithStateDirectory:(id)arg1;

@end

