//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSPortMessage;

@protocol NSPortDelegate <NSObject>

@optional
- (void)handlePortMessage:(NSPortMessage *)arg1;
@end

