//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSProxy.h>

@class NSGraphicsContext;

__attribute__((visibility("hidden")))
@interface NSPrintPreviewGraphicsContext : NSProxy
{
    NSGraphicsContext *_previousContext;
}

- (id)description;
- (BOOL)isFlipped;
- (BOOL)isDrawingToScreen;
- (id)attributes;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (void)dealloc;
- (id)initWithPreviousContext:(id)arg1;

@end

