//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <AppKit/NSPrintPanelAccessorizing-Protocol.h>

__attribute__((visibility("hidden")))
@interface NSPrintPanelOldAccessoryController : NSViewController <NSPrintPanelAccessorizing>
{
}

- (id)keyPathsForValuesAffectingPreview;
- (id)localizedSummaryItems;

@end

