//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol NSPrintGraphicsContextAdvancing
- (void)endDocument;
- (void)endPage;
- (void)beginPageWithBounds:(struct CGRect)arg1;
- (void)beginDocumentWithTitle:(NSString *)arg1;
@end

