//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSSet;

@protocol NSPrintPanelAccessorizing
- (NSArray *)localizedSummaryItems;

@optional
- (NSSet *)keyPathsForValuesAffectingPreview;
@end

