//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSOverlayScrollerImp.h>

__attribute__((visibility("hidden")))
@interface NSRegularOverlayScrollerImp : NSOverlayScrollerImp
{
}

+ (double)scrollerWidth;
- (double)trackOverlapEndInset;
- (double)knobInset;
- (double)knobMinLength;
- (double)trackSideInset;
- (double)trackEndInset;
- (double)_expandedTrackWidth;
- (double)trackWidth;
- (unsigned long long)controlSize;

@end

