//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSRulerMarker;

__attribute__((visibility("hidden")))
@interface NSRulerMarkerView : NSView
{
    NSRulerMarker *_rulerMarker;
}

- (BOOL)isFlipped;
- (void)drawRect:(struct CGRect)arg1;
- (void)setRulerMarker:(id)arg1;
- (id)rulerMarker;
- (void)updateFrame;
- (void)dealloc;

@end

