//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPanel.h>

__attribute__((visibility("hidden")))
@interface NSRulerMarkerPanel : NSPanel
{
}

- (BOOL)canBecomeVisibleWithoutLogin;
- (BOOL)hasShadow;

@end

