//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

__attribute__((visibility("hidden")))
@interface NSRuleEditorButton : NSButton
{
}

- (Class)classForCoder;

@end

