//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

__attribute__((visibility("hidden")))
@interface NSRuleEditorTextField : NSTextField
{
}

- (id)hitTest:(struct CGPoint)arg1;

@end

