//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class NSNumberFormatter;

__attribute__((visibility("hidden")))
@interface NSRulerLabelCell : NSTextFieldCell
{
    NSNumberFormatter *_auxiliaryFormatter;
}

- (void)dealloc;
- (void)_setAuxiliaryFormatter:(id)arg1;
- (id)_auxiliaryFormatter;
- (long long)_typesetterBehavior;

@end

