//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSRuleEditorViewSlice.h>

__attribute__((visibility("hidden")))
@interface NSRuleEditorViewSliceDropSeparator : NSRuleEditorViewSlice
{
}

- (void)drawRect:(struct CGRect)arg1;

@end

