//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButtonCell.h>

__attribute__((visibility("hidden")))
@interface NSRuleEditorPopupButtonCell : NSPopUpButtonCell
{
}

- (id)accessibilityEnabledAttribute;
- (unsigned long long)arrowPosition;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (BOOL)sliceIsEditable;

@end

