//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSRunLoop.h>

@interface NSRunLoop (NSDisplayLink)
- (void)removeDisplayLink:(id)arg1 forMode:(id)arg2;
- (void)addDisplayLink:(id)arg1 forMode:(id)arg2;
@end

