//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSOpenSavePanelDelegate-Protocol.h>

@class NSArray, NSSavePanel, NSSavePanelCustomAction;

@protocol NSSavePanelCustomActionDelegate <NSOpenSavePanelDelegate>
- (void)panel:(NSSavePanel *)arg1 customActionInvoked:(NSSavePanelCustomAction *)arg2 onItems:(NSArray *)arg3;
@end

