//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface NSScrollingBehaviorZombie
{
}

+ (id)zombieListDescription;
+ (id)zombieList;
- (id)description;
@property(retain) NSArray *backtrace;
@property(copy) NSString *originalClassName;
- (id)forwardingTargetForSelector:(SEL)arg1;

@end

