//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSScreenBackgroundView : NSView
{
}

- (void)drawRect:(struct CGRect)arg1;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (struct __CFDictionary *)_createUnderDesktopCUIOptionsDictionary;
- (BOOL)isOpaque;

@end

