//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSScrubberLayout, NSScrubberLayoutAttributes, NSSet, NSView;

@protocol NSScrubberItemLayout <NSObject>
@property(readonly) BOOL wantsTrackingPosition;
@property(retain) NSScrubberLayout *scrubberLayout;
- (void)invalidateForStateIfNeeded:(CDStruct_99688279)arg1;
- (NSScrubberLayoutAttributes *)itemLayoutAttributesForItemAtIndex:(long long)arg1 withState:(CDStruct_99688279)arg2 inView:(NSView *)arg3;
- (NSSet *)itemLayoutAttributesForState:(CDStruct_99688279)arg1 inView:(NSView *)arg2;
@end

