//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSScrollView.h>

__attribute__((visibility("hidden")))
@interface NSScrollViewNotResponsive : NSScrollView
{
}

+ (BOOL)isCompatibleWithResponsiveScrolling;

@end

