//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

__attribute__((visibility("hidden")))
@interface NSScrubberArrowButton : NSButton
{
    BOOL _isLeft;
}

+ (Class)cellClass;
- (long long)accessibilityIndex;
- (id)accessibilityLabel;
- (id)accessibilityRole;
- (BOOL)acceptsFirstResponder;
@property(readonly) BOOL arrowFacesLeft;
- (id)initWithArrowFacesLeft:(BOOL)arg1;

@end

