//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSStoryboardSegue, NSString;

@protocol NSSeguePerforming <NSObject>

@optional
- (BOOL)shouldPerformSegueWithIdentifier:(NSString *)arg1 sender:(id)arg2;
- (void)performSegueWithIdentifier:(NSString *)arg1 sender:(id)arg2;
- (void)prepareForSegue:(NSStoryboardSegue *)arg1 sender:(id)arg2;
@end

