//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSSet.h>

@interface NSSet (NSCollectionViewAdditions)
+ (id)setWithCollectionViewIndexPaths:(id)arg1;
+ (id)setWithCollectionViewIndexPath:(id)arg1;
- (void)enumerateIndexPathsWithOptions:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
@end

