//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextFieldDelegate-Protocol.h>

@class NSSearchField;

@protocol NSSearchFieldDelegate <NSTextFieldDelegate>

@optional
- (void)searchFieldDidEndSearching:(NSSearchField *)arg1;
- (void)searchFieldDidStartSearching:(NSSearchField *)arg1;
@end

