//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSServicesRolloverView, NSSharingServicePicker;

@protocol NSServicesRolloverViewDelegate <NSObject>
- (NSSharingServicePicker *)pickerForRolloverCalloutView:(NSServicesRolloverView *)arg1;
@end

