//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWidgetView.h>

__attribute__((visibility("hidden")))
@interface NSSegmentItemBezelView : NSWidgetView
{
}

- (void)viewDidChangeEffectiveAppearance;
- (int)_vibrancyBlendMode;
- (int)_defaultVibrancyBlendMode;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (BOOL)isAccessibilityElement;

@end

