//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SHKSharingService;
@protocol NSSharingServiceDelegate;

__attribute__((visibility("hidden")))
@interface NSSharingServiceReserved : NSObject
{
    id <NSSharingServiceDelegate> delegate;
    SHKSharingService *service;
}

- (void).cxx_destruct;
- (void)dealloc;

@end

