//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageCell.h>

__attribute__((visibility("hidden")))
@interface NSSidebarImageCell : NSImageCell
{
}

- (BOOL)_shouldClip;

@end

