//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSColor, NSColorSpace;

@protocol NSSliderViewRequiredMethods
+ (NSColorSpace *)genericColorSpace;
- (NSColor *)regularColorIfPossible:(NSColor *)arg1;
- (void)adjustControls:(id)arg1;
- (void)_adjustControls:(id)arg1 andSetColor:(BOOL)arg2;
- (void)setColor:(NSColor *)arg1;
- (id)provideNewSubview:(id)arg1;
@end

