//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSLegacyScrollerImp.h>

__attribute__((visibility("hidden")))
@interface NSSmallLegacyScrollerImp : NSLegacyScrollerImp
{
}

+ (double)scrollerWidth;
- (double)knobMinLength;
- (double)trackWidth;
- (unsigned long long)controlSize;

@end

