//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSSoundEngineDelegate;

@protocol NSSoundEngine <NSObject>
@property double currentTime;
@property(readonly) double duration;
- (id)initWithDelegate:(id <NSSoundEngineDelegate>)arg1;
- (void)channelMappingDidChange;
- (void)deviceUIDDidChange;
- (void)shouldLoopDidChange;
- (void)volumeDidChange;
- (void)resetPosition;
- (void)stop;
- (BOOL)play;
- (BOOL)resume;
- (BOOL)pause;
@end

