//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSStoryboardSegueTemplate.h>

#import <AppKit/NSCoding-Protocol.h>

@interface NSStoryboardModalSegueTemplate : NSStoryboardSegueTemplate <NSCoding>
{
}

- (CDUnknownBlockType)newDefaultPerformHandlerForSegue:(id)arg1;

@end

