//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSBaseTabData.h>

@class NSWindow;

__attribute__((visibility("hidden")))
@interface NSSyncedTabWrapper : NSBaseTabData
{
    NSWindow *_window;
    BOOL _snapshotIsDisabled;
}

- (void).cxx_destruct;
@property BOOL snapshotIsDisabled; // @synthesize snapshotIsDisabled=_snapshotIsDisabled;
@property(retain) NSWindow *window; // @synthesize window=_window;
- (void)dispose;

@end

