//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSClipView.h>

__attribute__((visibility("hidden")))
@interface NSTabBarClipView : NSClipView
{
    BOOL _shouldChangeNextScrollFromVerticalToHorizontal;
}

@property(nonatomic) BOOL shouldChangeNextScrollFromVerticalToHorizontal; // @synthesize shouldChangeNextScrollFromVerticalToHorizontal=_shouldChangeNextScrollFromVerticalToHorizontal;
- (BOOL)_scrollTo:(const struct CGPoint *)arg1 animateScroll:(long long)arg2 flashScrollerKnobs:(unsigned long long)arg3;
- (BOOL)_shouldDoLayerPerformanceUpdates;

@end

