//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSpringAnimation.h>

__attribute__((visibility("hidden")))
@interface NSTableRowViewSpringAnimation : NSSpringAnimation
{
    double _startPercentage;
    double _endPercentage;
}

@property double endPercentage; // @synthesize endPercentage=_endPercentage;
@property double startPercentage; // @synthesize startPercentage=_startPercentage;
- (id)initWithDuration:(double)arg1;
@property(readonly) double percentage;

@end

