//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSTabDraggingDestination, NSTabDraggingInfo;

@protocol NSTabDraggingWindowDestination <NSObject>

@optional
- (id <NSTabDraggingDestination>)destinationForTabDragOperation:(id <NSTabDraggingInfo>)arg1;
@end

