//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface NSTableViewSidebarDefaultIconSizeObserver : NSObject
{
}

+ (void)defaultRowSizeStyleChanged:(id)arg1;
+ (long long)readUserDefaultsValue;
+ (long long)currentRowSizeStyle;
+ (void)initialize;

@end

