//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTabBarDelayedPopUpButtonCell.h>

__attribute__((visibility("hidden")))
@interface NSTabBarNewTabButtonCell : NSTabBarDelayedPopUpButtonCell
{
}

- (void)drawImage:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;

@end

