//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableViewCellProxy.h>

__attribute__((visibility("hidden")))
@interface NSTableViewListCellProxy : NSTableViewCellProxy
{
}

- (void)accessibilitySetSelectedAttribute:(id)arg1;
- (BOOL)accessibilityIsSelectedAttributeSettable;
- (id)accessibilitySelectedAttribute;
- (id)accessibilitySizeAttribute;
- (id)accessibilityParentAttribute;
- (id)accessibilityAttributeNames;
- (BOOL)_canDeselect;

@end

