//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableUpdateItem2.h>

__attribute__((visibility("hidden")))
@interface NSTableUpdateMoveItem : NSTableUpdateItem2
{
}

- (id)initMoveWithOriginalRow:(long long)arg1;
- (id)initMoveWithOriginalRow:(long long)arg1 animation:(unsigned long long)arg2;

@end

