//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAutounbinder, NSView;

__attribute__((visibility("hidden")))
@interface NSTableCellViewAux : NSObject
{
    NSAutounbinder *autounbinder;
    NSView *contentView;
    unsigned int _doingLayout:1;
    unsigned int _isSourceList:1;
    unsigned int _isLegacySourceList:1;
}

@end

