//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableUpdateItem2.h>

@class NSTableRowView;

__attribute__((visibility("hidden")))
@interface NSTableUpdateDeleteItem : NSTableUpdateItem2
{
    NSTableRowView *_viewToDelete;
}

@property(retain, nonatomic) NSTableRowView *viewToDelete; // @synthesize viewToDelete=_viewToDelete;
- (void)dealloc;
- (id)initWithRowAnimation:(unsigned long long)arg1;

@end

