//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

__attribute__((visibility("hidden")))
@interface NSTabPickerWindow : NSWindow
{
}

- (struct CGSize)minSize;
- (BOOL)_supportsNewTabButton;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)performCloseTabbedWindowGroup:(id)arg1;
- (void)performClose:(id)arg1;
- (id)_tabBarItem;
- (void)toggleTabOverview:(id)arg1;

@end

