//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableUpdateItem2.h>

@class NSTableRowView;

__attribute__((visibility("hidden")))
@interface NSTableUpdateInsertItem : NSTableUpdateItem2
{
    NSTableRowView *_viewToAnimateFrom;
}

@property(retain, nonatomic) NSTableRowView *viewToAnimateFrom; // @synthesize viewToAnimateFrom=_viewToAnimateFrom;
- (void)dealloc;

@end

