//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSTabBarSyncedButtonDelegate;

@protocol NSTabBarSyncedButton <NSObject>
@property(nonatomic, getter=isSyncedWithOtherButton) BOOL syncedWithOtherButton;
@property(nonatomic) __weak id <NSTabBarSyncedButtonDelegate> buttonInTabSyncGroupDelegate;
- (void)setHighlightStateToPressed:(BOOL)arg1 hovered:(BOOL)arg2;
@end

