//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSTabBarSyncedButton;

@protocol NSTabBarSyncedButtonDelegate <NSObject>
- (void)button:(id <NSTabBarSyncedButton>)arg1 didSetHighlightStateToPressed:(BOOL)arg2 hovered:(BOOL)arg3;
@end

