//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableViewCellMockElement.h>

__attribute__((visibility("hidden")))
@interface NSTableViewListCellMockElement : NSTableViewCellMockElement
{
}

- (BOOL)accessibilityIsIndexAttributeSettable;
- (id)accessibilityIndexAttribute;
- (id)accessibilityParentAttribute;
- (id)accessibilityRoleAttribute;
- (id)accessibilityAttributeNames;

@end

