//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSImage, NSTabBarItem, NSWindow;

@protocol NSTabDraggingInfo <NSObject>
- (NSTabBarItem *)draggingItem;
- (id)draggingSource;
- (NSImage *)draggedImage;
- (struct CGPoint)draggingLocation;
- (unsigned long long)draggingSourceOperationMask;
- (NSWindow *)draggingDestinationWindow;
@end

