//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableViewCellProxy.h>

__attribute__((visibility("hidden")))
@interface NSTableViewChildCellProxy : NSTableViewCellProxy
{
}

- (id)accessibilitySizeAttribute;
- (id)accessibilityPositionAttribute;
- (struct CGRect)realElementRect;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)accessibilityParentAttribute;
- (void)dealloc;
- (id)initWithRow:(long long)arg1 tableColumn:(id)arg2 realElement:(id)arg3;

@end

