//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NSTextPlaceholderInternalVars : NSObject
{
    NSString *_identifier;
}

@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
- (void)dealloc;
- (id)init;

@end

