//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NSTextFinderBarTextField : NSTextField
{
}

@property(copy) NSString *statusString;

@end

