//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSComboBox.h>

__attribute__((visibility("hidden")))
@interface NSTexturedComboBox : NSComboBox
{
}

- (id)_cui_optionsForCurrentState;
- (struct NSEdgeInsets)alignmentRectInsets;
- (struct CGSize)intrinsicContentSize;

@end

