//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSArray.h>

@class NSTextStorage;

__attribute__((visibility("hidden")))
@interface NSTextStorageCharacterArray : NSArray
{
    NSTextStorage *_container;
}

- (id)objectAtIndex:(unsigned long long)arg1;
- (unsigned long long)count;
- (void)dealloc;
- (id)initWithContainer:(id)arg1;

@end

