//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol NSTextInputTraits

@optional
@property long long textCompletionType;
@property long long linkDetectionType;
@property long long dataDetectionType;
@property long long textReplacementType;
@property long long smartInsertDeleteType;
@property long long smartDashesType;
@property long long smartQuotesType;
@property long long grammarCheckingType;
@property long long spellCheckingType;
@property long long autocorrectionType;
@end

