//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CALayer.h>

__attribute__((visibility("hidden")))
@interface NSTextLayerForegroundLayer : CALayer
{
}

- (void)_renderForegroundInContext:(struct CGContext *)arg1;
- (id)init;

@end

