//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSView;

@protocol NSTextFinderBarContainer <NSObject>
@property(getter=isFindBarVisible) BOOL findBarVisible;
@property(retain) NSView *findBarView;
- (void)findBarViewDidChangeHeight;

@optional
- (NSView *)contentView;
@end

