//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSComboBoxCell.h>

__attribute__((visibility("hidden")))
@interface NSTexturedComboBoxCell : NSComboBoxCell
{
}

- (double)_textVerticalAdjust;
- (double)_textVerticalInset;
- (BOOL)_isToolbarComboBox;
- (BOOL)drawsBackground;

@end

