//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIFoundation/NSTextAttachment.h>

@interface NSTextAttachment (NSTextAttachmentAdditions)
+ (BOOL)_usesRollover;
- (void)_processAttachmentWithNewContentsOfItem:(id)arg1 hanlder:(CDUnknownBlockType)arg2;
- (BOOL)allowsEditingContents;
- (void)setAllowsEditingContents:(BOOL)arg1;
- (id)_immediateActionAnimationControllerForCharacterAtIndex:(unsigned long long)arg1 inTextView:(id)arg2;
@end

