//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NSTextReplacementNode : NSObject
{
    NSString *curString;
    NSString *replacementString;
    unsigned long long replacementFlags;
    NSTextReplacementNode *children[28];
}

- (void)dealloc;

@end

