//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageRep.h>

@class NSImage;

__attribute__((visibility("hidden")))
@interface NSTemplatizingImageRep : NSImageRep
{
    NSImage *_sourceImage;
}

- (BOOL)draw;
- (void)dealloc;
- (id)initWithSourceImage:(id)arg1;

@end

