//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface NSTextViewCompletionWindow : NSWindow
{
}

- (id)accessibilityParentAttribute;
- (BOOL)accessibilityIsChildOfApp;
- (BOOL)accessibilityIsIgnored;
- (BOOL)canBecomeVisibleWithoutLogin;

@end

