//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSearchField.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface NSTextFinderBarSearchField : NSSearchField
{
}

- (void)mouseDown:(id)arg1;
- (BOOL)needsPanelToBecomeKey;
- (BOOL)_mouseDownEventIsInSearchButton:(id)arg1;
@property(copy) NSArray *recentAttributedSearchStrings;
@property(copy) NSString *statusString;

@end

