//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

__attribute__((visibility("hidden")))
@interface NSThemeDocumentButtonCell : NSButtonCell
{
}

- (BOOL)_needRedrawOnWindowChangedKeyState;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (long long)_bezelPresentationStateInView:(id)arg1;
- (id)_appearanceContentStyleInView:(id)arg1;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (id)accessibilityTitleAttribute;
- (id)accessibilityRoleAttribute;

@end

