//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSProxy.h>

@class NSPathControl, NSThemeDocumentButton;

__attribute__((visibility("hidden")))
@interface NSThemeDocumentButtonPopUpMenuProxy : NSProxy
{
    id realObject;
    NSThemeDocumentButton *documentButton;
    NSPathControl *pathControl;
}

- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)createRealObjectIfNeeded;
- (void)dealloc;
- (id)initWithDocumentButton:(id)arg1;

@end

