//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

__attribute__((visibility("hidden")))
@interface NSTitleTextFieldCell : NSTextFieldCell
{
}

- (id)_appearanceContentStyleInView:(id)arg1;
- (BOOL)_shouldUseStyledTextInView:(id)arg1;

@end

