//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSTitlebarSeparatorView : NSView
{
    long long _type;
}

- (BOOL)ignoreHitTest;
- (struct CGSize)intrinsicContentSize;
- (void)_windowChangedKeyState;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (void)drawRect:(struct CGRect)arg1;
- (int)_vibrancyBlendMode;
- (BOOL)allowsVibrancy;
- (id)_cuiOptions;
@property long long type;

@end

