//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarProvider-Protocol.h>

@class NSArray, NSSet;

@protocol NSTouchBarProviderContainer <NSTouchBarProvider>
- (NSSet *)NS_touchBarProvidersKeyPaths;
- (NSArray *)NS_touchBarProviders;
@end

