//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarCustomizationPreviewSectionLayoutDelegate-Protocol.h>

@class NSTouchBarCustomizationPreviewMiniControlStripSectionLayout;

@protocol NSTouchBarCustomizationPreviewMiniControlStripSectionLayoutDelegate <NSTouchBarCustomizationPreviewSectionLayoutDelegate>
- (BOOL)requiresCompressedMiniControlStripForLayout:(NSTouchBarCustomizationPreviewMiniControlStripSectionLayout *)arg1;
@end

