//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSTouchBarPressAndHoldTransposer;

@protocol NSTouchBarPressAndHoldTransposerDelegate <NSObject>
- (void)transposerDidCancel:(NSTouchBarPressAndHoldTransposer *)arg1;
- (void)transposerDidEnd:(NSTouchBarPressAndHoldTransposer *)arg1;
@end

