//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@protocol NSTouchBarItemTypePopover <NSObject>
@property(readonly) BOOL isPresented;
- (void)dismissPopover:(id)arg1;
- (void)showPopover:(id)arg1;
@end

