//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSTouchBarItemAttributes : NSObject
{
    struct CGRect _frame;
    double _alphaValue;
    double _zPosition;
}

@property double zPosition; // @synthesize zPosition=_zPosition;
@property double alphaValue; // @synthesize alphaValue=_alphaValue;
@property struct CGRect frame; // @synthesize frame=_frame;
- (id)description;

@end

