//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSColor;

@protocol NSTouchBarColorPickerView <NSObject>
+ (long long)preferredColorSwatchType;
@property SEL action;
@property __weak id target;
@property BOOL allowsAlpha;
@property(copy) NSColor *currentColor;

@optional
- (void)showMostRecentSavedColor;
@end

