//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface NSToolbarCollectionViewItemView : NSView
{
    NSView *_contentView;
}

- (void).cxx_destruct;
@property __weak NSView *contentView; // @synthesize contentView=_contentView;
- (id)hitTest:(struct CGPoint)arg1;

@end

