//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSColor, NSString, NSTouchBarColorListPickerPressAndHoldPopUp;

@protocol NSTouchBarColorListPickerPressAndHoldPopUpDelegate <NSObject>
- (void)popUpDidEndColorSelection:(NSTouchBarColorListPickerPressAndHoldPopUp *)arg1 cancelled:(BOOL)arg2;
- (void)popUp:(NSTouchBarColorListPickerPressAndHoldPopUp *)arg1 didHighlightColor:(NSColor *)arg2 withKey:(NSString *)arg3 atIndex:(long long)arg4;
- (void)popUpDidDismiss:(NSTouchBarColorListPickerPressAndHoldPopUp *)arg1;
@end

