//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarItemTreeNode.h>

@class NSTouchBarItem;

@interface NSTouchBarItemTreeItemNode : NSTouchBarItemTreeNode
{
    NSTouchBarItem *_item;
}

+ (id)nodeForItem:(id)arg1;
@property(readonly) NSTouchBarItem *item; // @synthesize item=_item;
- (id)description;
- (void)dealloc;
- (id)initWithItem:(id)arg1;
- (id)initWithNode:(id)arg1 children:(id)arg2;
- (id)itemIdentifier;

@end

