//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarCustomizationPreviewSectionLayout.h>

__attribute__((visibility("hidden")))
@interface NSTouchBarCustomizationPreviewMiniControlStripSectionLayout : NSTouchBarCustomizationPreviewSectionLayout
{
    double _cachedGrabberMaxXPosition;
}

+ (Class)layoutAttributesClass;
@property(readonly) double cachedGrabberMaxXPosition; // @synthesize cachedGrabberMaxXPosition=_cachedGrabberMaxXPosition;
- (BOOL)canInsertItem:(id)arg1 atIndex:(long long)arg2;
- (id)canMoveItemAtIndex:(long long)arg1 toIndex:(long long)arg2 byRemovingItems:(id)arg3;
- (BOOL)canMoveItemAtIndex:(long long)arg1 toIndex:(long long)arg2;
- (void)prepareLayout;

@end

