//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCollectionViewDelegate-Protocol.h>

@class NSCollectionView, NSCollectionViewLayout, NSIndexPath;

@protocol NSTouchBarCustomizationPaletteLayoutDelegate <NSCollectionViewDelegate>
- (struct CGSize)collectionView:(NSCollectionView *)arg1 layout:(NSCollectionViewLayout *)arg2 maxSizeForItemAtIndexPath:(NSIndexPath *)arg3;
- (struct CGSize)collectionView:(NSCollectionView *)arg1 layout:(NSCollectionViewLayout *)arg2 minSizeForItemAtIndexPath:(NSIndexPath *)arg3;
@end

