//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCollectionView.h>

__attribute__((visibility("hidden")))
@interface NSTouchBarCustomizationPaletteCollectionView : NSCollectionView
{
}

- (id)collectionViewAccessibility;
- (BOOL)accessibilityIsIgnored;
- (BOOL)acceptsFirstResponder;
- (void)setFrameSize:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;

@end

