//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSImage, NSString;

__attribute__((visibility("hidden")))
@interface NSTouchBarColorPickerSwitcherItem : NSObject
{
    NSImage *_image;
    NSString *_label;
}

+ (id)itemWithLabel:(id)arg1 image:(id)arg2;
@property(copy) NSImage *image; // @synthesize image=_image;
@property(copy) NSString *label; // @synthesize label=_label;
- (void)dealloc;

@end

