//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAppearance.h>

__attribute__((visibility("hidden")))
@interface NSTouchBarReducedMetricsAppearance : NSAppearance
{
}

- (struct CGSize)_minimumSizeForStandardButton;
- (BOOL)_isFunctionRowAppearance;

@end

