//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSToolbarItem.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NSToolbarServicesItem : NSToolbarItem
{
    NSString *_representedObject;
}

- (id)_computeDefaultMenuFormRepresentation;
@property(readonly) id representedObject;
- (void)dealloc;
- (void)configureForDisplayMode:(unsigned long long)arg1 andSizeMode:(unsigned long long)arg2;
- (void)validate;
- (id)initWithItemIdentifier:(id)arg1;

@end

