//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSView;

@protocol NSTouchBarColorListPickerContainerView <NSObject>
@property BOOL active;
@property(retain) NSView *contentView;
@end

