//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSTouchBar;

@protocol NSTouchBarProvider <NSObject>
@property(readonly) NSTouchBar *touchBar;
@end

