//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSArray, NSTouchBarFinder;
@protocol NSTouchBarProviderContainer;

@protocol NSTouchBarFinderObserver <NSObject>
- (void)touchBarFinder:(NSTouchBarFinder *)arg1 updatedTouchBars:(NSArray *)arg2;

@optional
- (NSArray *)touchBarFinder:(NSTouchBarFinder *)arg1 touchBarProvidersForProviderContainer:(id <NSTouchBarProviderContainer>)arg2;
@end

