//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarColorPickerSliderArtworkProvider.h>

__attribute__((visibility("hidden")))
@interface NSTouchBarColorPickerSliderHSBArtworkProvider : NSTouchBarColorPickerSliderArtworkProvider
{
}

+ (id)brightnessArtworkProviderWithDisplayHue:(double)arg1 displaySaturation:(double)arg2;
+ (id)saturationArtworkProviderWithDisplayHue:(double)arg1;
+ (id)hueArtworkProvider;
@property(readonly) long long representedHSBComponent;

@end

