//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarCustomizationPreviewSectionLayout.h>

__attribute__((visibility("hidden")))
@interface NSTouchBarCustomizationPreviewFlexibleSectionLayout : NSTouchBarCustomizationPreviewSectionLayout
{
    double _defaultItemPadding;
    double _cachedVisualCenterXOffset;
}

@property double defaultItemPadding; // @synthesize defaultItemPadding=_defaultItemPadding;
- (BOOL)canInsertItem:(id)arg1 atIndex:(long long)arg2;
- (id)canMoveItemAtIndex:(long long)arg1 toIndex:(long long)arg2 byRemovingItems:(id)arg3;
- (void)prepareLayout;
- (id)initWithDelegate:(id)arg1 section:(long long)arg2;

@end

