//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSTouchBarCustomizationPaletteViewController, NSTouchBarItem;

@protocol NSTouchBarCustomizationPaletteViewControllerDelegate <NSObject>
- (void)controllerAccessibilityResetTouchBar:(NSTouchBarCustomizationPaletteViewController *)arg1;
- (void)controller:(NSTouchBarCustomizationPaletteViewController *)arg1 accessibilityAddItem:(NSTouchBarItem *)arg2;
- (void)controllerDidEndDragging:(NSTouchBarCustomizationPaletteViewController *)arg1;
- (void)controllerWillBeginDragging:(NSTouchBarCustomizationPaletteViewController *)arg1;
@end

