//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/NSCopying-Protocol.h>

@class NSTouchBarItemTreeNode;
@protocol NSTouchBarItemTreeParentNode;

@interface NSTouchBarItemTreePosition : NSObject <NSCopying>
{
    NSTouchBarItemTreeNode<NSTouchBarItemTreeParentNode> *_parentNode;
    long long _indexInParent;
}

+ (id)positionInParentNode:(id)arg1 atIndex:(long long)arg2;
@property(readonly, copy) NSTouchBarItemTreeNode<NSTouchBarItemTreeParentNode> *parentNode; // @synthesize parentNode=_parentNode;
@property(readonly) long long indexInParent; // @synthesize indexInParent=_indexInParent;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;

@end

