//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NSToolbarLabel : NSTextField
{
}

- (void)setBordered:(BOOL)arg1;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)arg1;
@property(copy) NSString *title;
- (id)init;

@end

