//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarCustomizationPreviewSectionLayoutDelegate-Protocol.h>

@class NSTouchBarCustomizationPreviewFlexibleSectionLayout;

@protocol NSTouchBarCustomizationPreviewFlexibleSectionLayoutDelegate <NSTouchBarCustomizationPreviewSectionLayoutDelegate>
- (double)visualCenterXOffsetForSectionLayout:(NSTouchBarCustomizationPreviewFlexibleSectionLayout *)arg1;
@end

