//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIFoundation/NSCollectionViewLayoutAttributes.h>

__attribute__((visibility("hidden")))
@interface NSTouchBarCustomizationPaletteLayoutAttributes : NSCollectionViewLayoutAttributes
{
    double _scaleFactor;
}

@property double scaleFactor; // @synthesize scaleFactor=_scaleFactor;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

