//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCollectionViewSectionAccessibility.h>

__attribute__((visibility("hidden")))
@interface NSTouchBarCustomizationPreviewLayoutSectionAccessibility : NSCollectionViewSectionAccessibility
{
}

- (id)accessibilityIdentifier;
- (id)accessibilityLabel;
- (BOOL)accessibilityIsHiddenAttributeSettable;
- (id)accessibilityHiddenAttribute;
- (BOOL)isAccessibilityHidden;
- (struct CGRect)accessibilityFrame;
- (id)sectionLayoutDelegate;
- (id)sectionLayout;

@end

