//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTouchBarCustomizationPreviewLayoutAttributes.h>

__attribute__((visibility("hidden")))
@interface NSTouchBarCustomizationPreviewMiniControlStripLayoutAttributes : NSTouchBarCustomizationPreviewLayoutAttributes
{
    double _leftCornerRadius;
    double _rightCornerRadius;
}

@property double rightCornerRadius; // @synthesize rightCornerRadius=_rightCornerRadius;
@property double leftCornerRadius; // @synthesize leftCornerRadius=_leftCornerRadius;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;

@end

