//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSTouchBarColorPickerSwitcher;

@protocol NSTouchBarColorPickerSwitcherDelegate <NSObject>
- (void)switcher:(NSTouchBarColorPickerSwitcher *)arg1 didSelectItemAtIndex:(long long)arg2;
@end

