//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSArray, NSTouchBar;

@protocol NSTouchBarAnimationDelegate <NSObject>
- (BOOL)touchBar:(NSTouchBar *)arg1 shouldAnimateFromIdentifiers:(NSArray *)arg2 toIdentifiers:(NSArray *)arg3;
@end

