//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface NSTrackingAreaReservedIVars : NSObject
{
    char *outstandingRolloverDelayCancelledPtr;
    NSArray *_pressureConfigurations;
}

- (void)dealloc;

@end

