//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPanel.h>

@class NSString, NSTextField;

__attribute__((visibility("hidden")))
@interface NSTypeSelectPanel : NSPanel
{
    NSTextField *_currentSeachTextField;
}

- (void)setCurrentSearchScreenRect:(struct CGRect)arg1;
@property(copy) NSString *currentSearch; // @dynamic currentSearch;
- (void)_ensureCurrentSearchTextField;
- (void)dealloc;
- (id)init;

@end

