//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSUserActivity;

@protocol NSUIActivityProvider <NSObject>
@property(retain) NSUserActivity *userActivity;
- (void)_cleanUpUserActivity;
- (void)_didRestoreUserActivity:(NSUserActivity *)arg1;
- (void)_becomeCurrentUserActivityIfNecessary;
- (void)userActivityWasContinued:(NSUserActivity *)arg1;
- (void)restoreUserActivityState:(NSUserActivity *)arg1;
- (void)updateUserActivityState:(NSUserActivity *)arg1;
@end

