//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSUndoTextOperation.h>

@class _NSAttributeRun;

@interface NSUndoSetAttributes : NSUndoTextOperation
{
    _NSAttributeRun *_attributes;
}

- (void)undoRedo:(id)arg1;
- (void)dealloc;
- (id)initWithAffectedRange:(struct _NSRange)arg1 textStorage:(id)arg2 undoManager:(id)arg3;

@end

