//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSUserInterfaceCompressionOptions;

@protocol NSUserInterfaceCompression
@property(readonly, copy) NSUserInterfaceCompressionOptions *activeCompressionOptions;
- (struct CGSize)minimumSizeWithPrioritizedCompressionOptions:(NSArray *)arg1;
- (void)compressWithPrioritizedCompressionOptions:(NSArray *)arg1;
@end

