//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol NSValidatedUserInterfaceItem
@property(readonly) long long tag;
@property(readonly) SEL action;
@end

