//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValue.h>

@interface NSValue (UIKitStubs)
+ (id)_valueWithCGRect:(struct CGRect)arg1;
+ (id)_valueWithCGPoint:(struct CGPoint)arg1;
@end

