//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSRolloverButton.h>

__attribute__((visibility("hidden")))
@interface NSVisualTabPickerToolbarButton : NSRolloverButton
{
}

- (void)mouseDown:(id)arg1;

@end

