//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSVisualTabPickerThumbnailView;

@protocol NSVisualTabPickerThumbnailDelegate <NSObject>
- (void)didCloseVisualTabPickerThumbnailView:(NSVisualTabPickerThumbnailView *)arg1;
- (void)didSelectVisualTabPickerThumbnailView:(NSVisualTabPickerThumbnailView *)arg1;
- (BOOL)canCloseTabInNSVisualTabPickerThumbnailView:(NSVisualTabPickerThumbnailView *)arg1;
@end

