//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSearchFieldDelegate-Protocol.h>

@class NSVisualTabPickerSearchField;

@protocol NSVisualTabPickerSearchFieldDelegate <NSSearchFieldDelegate>
- (void)visualTabPickerSearchFieldTextDidChange:(NSVisualTabPickerSearchField *)arg1;
@end

