//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/_NSSafariTransformLayer.h>

__attribute__((visibility("hidden")))
@interface NSVisualTabPickerClipViewLayer : _NSSafariTransformLayer
{
}

- (struct CGPoint)anchorPoint;
- (void)setAnchorPoint:(struct CGPoint)arg1;

@end

