//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewBuffer.h>

@class NSImage, NSWindow;

__attribute__((visibility("hidden")))
@interface NSViewWindowBackingStoreBuffer : NSViewBuffer
{
    NSWindow *_window;
    struct CGRect _windowRect;
    struct CGRect _savedRect;
    NSImage *_savedImage;
}

- (BOOL)restore;
- (BOOL)cacheRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithView:(id)arg1;

@end

