//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSArray, NSImage, NSTabBarItem, NSView, NSVisualTabPickerGridView;

@protocol NSVisualTabPickerGridViewDataSource <NSObject>
- (BOOL)visualTabPickerGridView:(NSVisualTabPickerGridView *)arg1 highlightStateForTabItem:(NSTabBarItem *)arg2;
- (double)tilesHeightToWidthRatioInVisualTabPickerGridView:(NSVisualTabPickerGridView *)arg1;
- (NSImage *)visualTabPickerGridView:(NSVisualTabPickerGridView *)arg1 imageForTabItem:(NSTabBarItem *)arg2;
- (NSView *)visualTabPickerGridView:(NSVisualTabPickerGridView *)arg1 thumbnailViewForTabItem:(NSTabBarItem *)arg2;
- (NSTabBarItem *)selectedTabItemInVisualTabPickerGridView:(NSVisualTabPickerGridView *)arg1;
- (NSArray *)orderedTabItemsInVisualTabPickerGridView:(NSVisualTabPickerGridView *)arg1;
@end

