//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSearchFieldCell.h>

__attribute__((visibility("hidden")))
@interface NSVisualTabPickerSearchFieldCell : NSSearchFieldCell
{
}

- (BOOL)_isToolbarMode;

@end

