//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewControllerWindowTransition.h>

__attribute__((visibility("hidden")))
@interface NSViewControllerUtilityWindowTransition : NSViewControllerWindowTransition
{
}

- (id)_makeWindowWithContentRect:(struct CGRect)arg1;

@end

