//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCGSContext.h>

@interface NSWindowGraphicsContext : NSCGSContext
{
    unsigned int _cgsWindowID;
}

- (BOOL)isDrawingToScreen;
- (unsigned int)windowID;
- (id)attributes;
- (id)initWithWindow:(id)arg1;
- (id)_initWithWindowNumber:(long long)arg1;

@end

