//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSWindow;

@protocol NSWindowSwiftUIDelegate <NSObject>

@optional
- (id)_accessibilityWindow:(NSWindow *)arg1 focusedUIElementOverrideWithCurrentValue:(id)arg2;
- (void)_accessibilityDidHitTestWindow:(NSWindow *)arg1;
- (void)_accessibilityWillHitTestWindow:(NSWindow *)arg1;
@end

