//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSWindow;

__attribute__((visibility("hidden")))
@interface NSWindowMenuItem : NSObject
{
    NSWindow *_window;
    NSString *_path;
    NSString *_title;
}

@property(copy) NSString *title; // @synthesize title=_title;
@property(retain) NSString *path; // @synthesize path=_path;
@property NSWindow *window; // @synthesize window=_window;
- (void)dealloc;

@end

