//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSWorkspaceAuthorization : NSObject
{
    id _private;
}

- (id)data;
- (void)dealloc;
- (id)initWithAuthorizationRef:(struct AuthorizationOpaqueRef *)arg1 ofType:(long long)arg2;

@end

