//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSAppleEventDescriptor;

@protocol BADescriptorTranslation

@optional
- (NSAppleEventDescriptor *)__shim;
- (NSAppleEventDescriptor *)__descriptor;
@end

