//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptObjC/BAGenericObject.h>

__attribute__((visibility("hidden")))
@interface BAGenericObjectNoDeleteOSAID : BAGenericObject
{
}

- (void)dealloc;

@end

