//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptObjC/BAObjectProto.h>

__attribute__((visibility("hidden")))
@interface BAGenericObject : BAObjectProto
{
    struct ComponentInstanceRecord *m_ci;
    unsigned int m_oid;
}

@end

