//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface ASKActiveProcSupport : NSObject
{
    CDUnknownFunctionPointerType _oldActiveProc;
    CDUnknownFunctionPointerType _activeProc;
}

+ (id)sharedActiveProcSupport;
- (void)setup;
- (void)didFinishLaunching:(id)arg1;
- (id)init;

@end

