//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKEventHandlerDelegate.h>

@interface ASKControlEventHandlerDelegate : ASKEventHandlerDelegate
{
}

- (BOOL)control:(id)arg1 textShouldEndEditing:(id)arg2;
- (BOOL)control:(id)arg1 textShouldBeginEditing:(id)arg2;

@end

