//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKMenuEventHandler.h>

@interface ASKChooseMenuItemEventHandler : ASKMenuEventHandler
{
}

- (void)chooseMenuItem:(id)arg1;
- (void)disable;
- (void)enable;

@end

