//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKScriptCommand.h>

@class ASKDisplayDialog;

@interface ASKDisplayDialogScriptCommand : ASKScriptCommand
{
    ASKDisplayDialog *_displayDialog;
}

- (id)performDefaultImplementation;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)setReceiversSpecifier:(id)arg1;
- (void)setDirectParameter:(id)arg1;
- (id)displayDialog;
- (void)dealloc;
- (id)initWithCommandDescription:(id)arg1;

@end

