//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKEventHandlerDelegate.h>

@interface ASKDrawerEventHandlerDelegate : ASKEventHandlerDelegate
{
}

- (struct CGSize)drawerWillResizeContents:(id)arg1 toSize:(struct CGSize)arg2;
- (BOOL)drawerShouldClose:(id)arg1;
- (BOOL)drawerShouldOpen:(id)arg1;

@end

