//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKEventHandlerDelegate.h>

@interface ASKDocumentEventHandlerDelegate : ASKEventHandlerDelegate
{
}

- (BOOL)document:(id)arg1 writeToURL:(id)arg2 ofType:(id)arg3 error:(id *)arg4;
- (BOOL)document:(id)arg1 readFromURL:(id)arg2 ofType:(id)arg3 error:(id *)arg4;
- (BOOL)document:(id)arg1 readFromData:(id)arg2 ofType:(id)arg3 error:(id *)arg4;
- (id)document:(id)arg1 dataOfType:(id)arg2 error:(id *)arg3;

@end

