//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ASKEventHandler;

@interface ASKEventHandlerImplementor : NSObject
{
    ASKEventHandler *_eventHandler;
}

- (void)disable;
- (void)enable;
- (void)setEventHandler:(id)arg1;
- (id)eventHandler;
- (void)dealloc;
- (id)initWithEventHandler:(id)arg1;

@end

