//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKScriptCommand.h>

@interface ASKLoadSoundScriptCommand : ASKScriptCommand
{
}

- (id)performDefaultImplementation;

@end

