//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKMouseEventHandler.h>

@interface ASKMouseExitedEventHandler : ASKMouseEventHandler
{
}

- (void)eventNotification:(id)arg1;
- (void)disable;
- (void)enable;

@end

