//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKEventHandler.h>

@class ASKMenuEventTarget;

@interface ASKMenuEventHandler : ASKEventHandler
{
    ASKMenuEventTarget *_target;
}

- (id)getAppleEventFromNotification:(id)arg1;
- (id)getAppleEvent;
- (void)disable;
- (void)enable;
- (void)setTarget:(id)arg1;
- (id)target;
- (void)dealloc;
- (id)initWithObject:(id)arg1 eventHandlerDescription:(id)arg2 enable:(BOOL)arg3;
- (id)init;
- (Class)eventImplementorClass;

@end

