//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSView;

@interface ASKMouseTracker : NSObject
{
    NSView *_view;
    long long _trackingTag;
}

- (void)frameChanged:(id)arg1;
- (void)finalize;
- (void)dealloc;
- (id)initWithView:(id)arg1;

@end

