//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface ASKPluginObject : NSObject
{
}

+ (void)pluginDidLoad:(id)arg1;
+ (void)initialize;

@end

