//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSAScript.h>

@interface ASKScript : OSAScript
{
}

- (long long)lineNumberForRange:(struct _NSRange)arg1;
- (id)propertyNames;
- (id)eventHandlerNames;
- (id)handlerNames;

@end

