//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptCommand.h>

@interface ASKScriptCommand : NSScriptCommand
{
}

- (id)performDefaultImplementation;
- (void)setReceiversSpecifier:(id)arg1;
- (void)setDirectParameter:(id)arg1;
- (id)initWithCommandDescription:(id)arg1;

@end

