//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAKit/OSAScriptParser.h>

@interface ASKScriptParser : OSAScriptParser
{
}

- (id)getEventHandlerElementFromBuffer:(struct _NSStringBuffer *)arg1;

@end

