//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKEventHandlerImplementor.h>

@interface ASKTargetActionEventHandlerImplementor : ASKEventHandlerImplementor
{
}

- (void)disable;
- (void)enable;

@end

