//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppleScriptKit/ASKEventHandler.h>

@interface ASKTextEventHandler : ASKEventHandler
{
}

- (id)getAppleEventFromNotification:(id)arg1;

@end

