//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSBrowserCell.h>

@interface NSBrowserCell (ASKDataViewSuite)
- (id)objectSpecifier;
- (void)setBrowser:(id)arg1;
- (id)browser;
- (void)setIsLoaded:(BOOL)arg1;
- (void)setIsLeaf:(BOOL)arg1;
@end

