//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSBrowser.h>

@interface NSBrowser (ASKContainerName)
+ (id)containerName_ask;
- (id)handlePathForScriptCommand:(id)arg1;
- (id)handleUpdateScriptCommand:(id)arg1;
- (void)setDisplayedCell:(id)arg1;
- (id)displayedCell;
- (void)setIsTitled:(BOOL)arg1;
@end

