//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSBundle.h>

@interface NSBundle (ASKApplicationSuite)
- (id)handlePathForScriptCommand:(id)arg1;
- (id)objectSpecifier;
- (unsigned long long)objectIndex_ask;
- (id)scriptsPath;
@end

