//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface NSButtonCell (ASKControlViewSuite)
- (void)setImagePosition_ask:(unsigned long long)arg1;
- (unsigned long long)imagePosition_ask;
- (void)setButtonType_ask:(unsigned long long)arg1;
- (unsigned long long)buttonType_ask;
- (void)setBezelStyle_ask:(unsigned long long)arg1;
- (unsigned long long)bezelStyle_ask;
- (void)setIsTransparent:(BOOL)arg1;
@end

