//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSClipView.h>

@interface NSClipView (ASKContainerName)
+ (id)containerName_ask;
- (id)documentVisibleRect_ask;
- (id)documentRect_ask;
@end

