//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColorPanel.h>

@interface NSColorPanel (ASKPanelSuite)
- (id)objectSpecifier;
- (void)setMode_ask:(unsigned long long)arg1;
- (unsigned long long)mode_ask;
- (void)setIsContinuous:(BOOL)arg1;
@end

