//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSColorWell.h>

@interface NSColorWell (ASKContainerName)
+ (id)containerName_ask;
- (void)setIsBordered:(BOOL)arg1;
@end

