//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (ASKApplicationSuite)
- (id)objectSpecifier;
- (unsigned long long)objectIndex_ask;
@end

