//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSOutlineView.h>

@interface NSOutlineView (ASKContainerName)
+ (id)containerName_ask;
- (id)handleItemForScriptCommand:(id)arg1;
- (id)handleUpdateScriptCommand:(id)arg1;
- (void)setSelectedDataItems:(id)arg1;
- (id)selectedDataItems;
- (void)setSelectedDataItem:(id)arg1;
- (id)selectedDataItem;
- (id)editedDataItem;
- (id)clickedDataItem;
@end

