//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPanel.h>

@interface NSPanel (ASKPanelSuite)
- (id)handleDisplayPanelScriptCommand:(id)arg1;
- (id)handleClosePanelScriptCommand:(id)arg1;
- (void)setIsFloatingPanel:(BOOL)arg1;
@end

