//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@interface NSPopUpButton (ASKContainerName)
+ (id)containerName_ask;
- (void)setPreferredEdge_ask:(unsigned long long)arg1;
- (unsigned long long)preferredEdge_ask;
- (void)setSelectedItem:(id)arg1;
@end

