//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSProgressIndicator.h>

@interface NSProgressIndicator (ASKContainerName)
+ (id)containerName_ask;
- (id)handleStopScriptCommand:(id)arg1;
- (id)handleStartScriptCommand:(id)arg1;
- (id)handleIncrementScriptCommand:(id)arg1;
- (id)handleAnimateScriptCommand:(id)arg1;
- (void)setControlTint_ask:(unsigned long long)arg1;
- (unsigned long long)controlTint_ask;
- (void)setControlSize_ask:(unsigned long long)arg1;
- (unsigned long long)controlSize_ask;
- (void)setIsIndeterminate:(BOOL)arg1;
- (void)setIsBezeled:(BOOL)arg1;
- (void)setContent:(double)arg1;
- (double)content;
@end

