//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSResponder.h>

@interface NSResponder (ASKApplicationSuite)
- (void)_postEventNotification:(id)arg1;
@end

