//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSScriptCoercionHandler.h>

@interface NSScriptCoercionHandler (ASKCoercions)
+ (id)coerceScript:(id)arg1 toString:(Class)arg2;
+ (id)coerceString:(id)arg1 toScript:(Class)arg2;
- (void)_setUpAppleScriptKitCoercions;
@end

