//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSlider.h>

@interface NSSlider (ASKContainerName)
+ (id)containerName_ask;
- (void)setTickMarkPosition_ask:(unsigned long long)arg1;
- (unsigned long long)tickMarkPosition_ask;
@end

