//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSound.h>

@interface NSSound (ASKApplicationSuite)
- (id)handleStopScriptCommand:(id)arg1;
- (id)handleResumeScriptCommand:(id)arg1;
- (id)handlePlayScriptCommand:(id)arg1;
- (id)handlePauseScriptCommand:(id)arg1;
@end

