//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTabViewItem.h>

@interface NSTabViewItem (ASKContainerViewSuite)
- (id)objectSpecifier;
- (unsigned long long)objectIndex_ask;
- (unsigned long long)tabState_ask;
@end

