//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableColumn.h>

@interface NSTableColumn (ASKDataViewSuite)
- (id)objectSpecifier;
- (unsigned long long)objectIndex_ask;
- (void)setIsEditable:(BOOL)arg1;
- (void)setIsResizable:(BOOL)arg1;
@end

