//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface NSTextField (ASKContainerName)
+ (id)containerName_ask;
- (void)setIsSelectable:(BOOL)arg1;
- (void)setIsEditable:(BOOL)arg1;
- (void)setIsBordered:(BOOL)arg1;
- (void)setIsBezeled:(BOOL)arg1;
- (void)textDidEndEditing_askTextField:(id)arg1;
- (void)textDidBeginEditing_askTextField:(id)arg1;
@end

